// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cal_common_key_proto.proto

package com.test.proto;

public final class CalCommonKeyProto {
  private CalCommonKeyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CalCommonKeyRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CalCommonKeyRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    int getVoteId();
  }
  /**
   * Protobuf type {@code CalCommonKeyRequest}
   */
  public  static final class CalCommonKeyRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CalCommonKeyRequest)
      CalCommonKeyRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CalCommonKeyRequest.newBuilder() to construct.
    private CalCommonKeyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CalCommonKeyRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CalCommonKeyRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CalCommonKeyRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              voteId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.CalCommonKeyProto.internal_static_CalCommonKeyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.CalCommonKeyProto.internal_static_CalCommonKeyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.CalCommonKeyProto.CalCommonKeyRequest.class, com.test.proto.CalCommonKeyProto.CalCommonKeyRequest.Builder.class);
    }

    public static final int VOTEID_FIELD_NUMBER = 1;
    private int voteId_;
    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    public int getVoteId() {
      return voteId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (voteId_ != 0) {
        output.writeInt32(1, voteId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (voteId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, voteId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.proto.CalCommonKeyProto.CalCommonKeyRequest)) {
        return super.equals(obj);
      }
      com.test.proto.CalCommonKeyProto.CalCommonKeyRequest other = (com.test.proto.CalCommonKeyProto.CalCommonKeyRequest) obj;

      if (getVoteId()
          != other.getVoteId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOTEID_FIELD_NUMBER;
      hash = (53 * hash) + getVoteId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.proto.CalCommonKeyProto.CalCommonKeyRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.CalCommonKeyProto.CalCommonKeyRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CalCommonKeyRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CalCommonKeyRequest)
        com.test.proto.CalCommonKeyProto.CalCommonKeyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.CalCommonKeyProto.internal_static_CalCommonKeyRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.CalCommonKeyProto.internal_static_CalCommonKeyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.CalCommonKeyProto.CalCommonKeyRequest.class, com.test.proto.CalCommonKeyProto.CalCommonKeyRequest.Builder.class);
      }

      // Construct using com.test.proto.CalCommonKeyProto.CalCommonKeyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        voteId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.CalCommonKeyProto.internal_static_CalCommonKeyRequest_descriptor;
      }

      @java.lang.Override
      public com.test.proto.CalCommonKeyProto.CalCommonKeyRequest getDefaultInstanceForType() {
        return com.test.proto.CalCommonKeyProto.CalCommonKeyRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.proto.CalCommonKeyProto.CalCommonKeyRequest build() {
        com.test.proto.CalCommonKeyProto.CalCommonKeyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.proto.CalCommonKeyProto.CalCommonKeyRequest buildPartial() {
        com.test.proto.CalCommonKeyProto.CalCommonKeyRequest result = new com.test.proto.CalCommonKeyProto.CalCommonKeyRequest(this);
        result.voteId_ = voteId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.CalCommonKeyProto.CalCommonKeyRequest) {
          return mergeFrom((com.test.proto.CalCommonKeyProto.CalCommonKeyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.CalCommonKeyProto.CalCommonKeyRequest other) {
        if (other == com.test.proto.CalCommonKeyProto.CalCommonKeyRequest.getDefaultInstance()) return this;
        if (other.getVoteId() != 0) {
          setVoteId(other.getVoteId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.CalCommonKeyProto.CalCommonKeyRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.CalCommonKeyProto.CalCommonKeyRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int voteId_ ;
      /**
       * <code>int32 voteId = 1;</code>
       * @return The voteId.
       */
      public int getVoteId() {
        return voteId_;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @param value The voteId to set.
       * @return This builder for chaining.
       */
      public Builder setVoteId(int value) {
        
        voteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteId() {
        
        voteId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CalCommonKeyRequest)
    }

    // @@protoc_insertion_point(class_scope:CalCommonKeyRequest)
    private static final com.test.proto.CalCommonKeyProto.CalCommonKeyRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.CalCommonKeyProto.CalCommonKeyRequest();
    }

    public static com.test.proto.CalCommonKeyProto.CalCommonKeyRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalCommonKeyRequest>
        PARSER = new com.google.protobuf.AbstractParser<CalCommonKeyRequest>() {
      @java.lang.Override
      public CalCommonKeyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalCommonKeyRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CalCommonKeyRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalCommonKeyRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.proto.CalCommonKeyProto.CalCommonKeyRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CalCommonKeyResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CalCommonKeyResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    int getVoteId();

    /**
     * <code>int32 statusCode = 2;</code>
     * @return The statusCode.
     */
    int getStatusCode();

    /**
     * <code>bytes commonKey = 3;</code>
     * @return The commonKey.
     */
    com.google.protobuf.ByteString getCommonKey();
  }
  /**
   * Protobuf type {@code CalCommonKeyResponse}
   */
  public  static final class CalCommonKeyResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CalCommonKeyResponse)
      CalCommonKeyResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CalCommonKeyResponse.newBuilder() to construct.
    private CalCommonKeyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CalCommonKeyResponse() {
      commonKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CalCommonKeyResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CalCommonKeyResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              voteId_ = input.readInt32();
              break;
            }
            case 16: {

              statusCode_ = input.readInt32();
              break;
            }
            case 26: {

              commonKey_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.CalCommonKeyProto.internal_static_CalCommonKeyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.CalCommonKeyProto.internal_static_CalCommonKeyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.CalCommonKeyProto.CalCommonKeyResponse.class, com.test.proto.CalCommonKeyProto.CalCommonKeyResponse.Builder.class);
    }

    public static final int VOTEID_FIELD_NUMBER = 1;
    private int voteId_;
    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    public int getVoteId() {
      return voteId_;
    }

    public static final int STATUSCODE_FIELD_NUMBER = 2;
    private int statusCode_;
    /**
     * <code>int32 statusCode = 2;</code>
     * @return The statusCode.
     */
    public int getStatusCode() {
      return statusCode_;
    }

    public static final int COMMONKEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString commonKey_;
    /**
     * <code>bytes commonKey = 3;</code>
     * @return The commonKey.
     */
    public com.google.protobuf.ByteString getCommonKey() {
      return commonKey_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (voteId_ != 0) {
        output.writeInt32(1, voteId_);
      }
      if (statusCode_ != 0) {
        output.writeInt32(2, statusCode_);
      }
      if (!commonKey_.isEmpty()) {
        output.writeBytes(3, commonKey_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (voteId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, voteId_);
      }
      if (statusCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, statusCode_);
      }
      if (!commonKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, commonKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.proto.CalCommonKeyProto.CalCommonKeyResponse)) {
        return super.equals(obj);
      }
      com.test.proto.CalCommonKeyProto.CalCommonKeyResponse other = (com.test.proto.CalCommonKeyProto.CalCommonKeyResponse) obj;

      if (getVoteId()
          != other.getVoteId()) return false;
      if (getStatusCode()
          != other.getStatusCode()) return false;
      if (!getCommonKey()
          .equals(other.getCommonKey())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOTEID_FIELD_NUMBER;
      hash = (53 * hash) + getVoteId();
      hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusCode();
      hash = (37 * hash) + COMMONKEY_FIELD_NUMBER;
      hash = (53 * hash) + getCommonKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.proto.CalCommonKeyProto.CalCommonKeyResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.CalCommonKeyProto.CalCommonKeyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.CalCommonKeyProto.CalCommonKeyResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CalCommonKeyResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CalCommonKeyResponse)
        com.test.proto.CalCommonKeyProto.CalCommonKeyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.CalCommonKeyProto.internal_static_CalCommonKeyResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.CalCommonKeyProto.internal_static_CalCommonKeyResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.CalCommonKeyProto.CalCommonKeyResponse.class, com.test.proto.CalCommonKeyProto.CalCommonKeyResponse.Builder.class);
      }

      // Construct using com.test.proto.CalCommonKeyProto.CalCommonKeyResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        voteId_ = 0;

        statusCode_ = 0;

        commonKey_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.CalCommonKeyProto.internal_static_CalCommonKeyResponse_descriptor;
      }

      @java.lang.Override
      public com.test.proto.CalCommonKeyProto.CalCommonKeyResponse getDefaultInstanceForType() {
        return com.test.proto.CalCommonKeyProto.CalCommonKeyResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.proto.CalCommonKeyProto.CalCommonKeyResponse build() {
        com.test.proto.CalCommonKeyProto.CalCommonKeyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.proto.CalCommonKeyProto.CalCommonKeyResponse buildPartial() {
        com.test.proto.CalCommonKeyProto.CalCommonKeyResponse result = new com.test.proto.CalCommonKeyProto.CalCommonKeyResponse(this);
        result.voteId_ = voteId_;
        result.statusCode_ = statusCode_;
        result.commonKey_ = commonKey_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.CalCommonKeyProto.CalCommonKeyResponse) {
          return mergeFrom((com.test.proto.CalCommonKeyProto.CalCommonKeyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.CalCommonKeyProto.CalCommonKeyResponse other) {
        if (other == com.test.proto.CalCommonKeyProto.CalCommonKeyResponse.getDefaultInstance()) return this;
        if (other.getVoteId() != 0) {
          setVoteId(other.getVoteId());
        }
        if (other.getStatusCode() != 0) {
          setStatusCode(other.getStatusCode());
        }
        if (other.getCommonKey() != com.google.protobuf.ByteString.EMPTY) {
          setCommonKey(other.getCommonKey());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.CalCommonKeyProto.CalCommonKeyResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.CalCommonKeyProto.CalCommonKeyResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int voteId_ ;
      /**
       * <code>int32 voteId = 1;</code>
       * @return The voteId.
       */
      public int getVoteId() {
        return voteId_;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @param value The voteId to set.
       * @return This builder for chaining.
       */
      public Builder setVoteId(int value) {
        
        voteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteId() {
        
        voteId_ = 0;
        onChanged();
        return this;
      }

      private int statusCode_ ;
      /**
       * <code>int32 statusCode = 2;</code>
       * @return The statusCode.
       */
      public int getStatusCode() {
        return statusCode_;
      }
      /**
       * <code>int32 statusCode = 2;</code>
       * @param value The statusCode to set.
       * @return This builder for chaining.
       */
      public Builder setStatusCode(int value) {
        
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 statusCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusCode() {
        
        statusCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString commonKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes commonKey = 3;</code>
       * @return The commonKey.
       */
      public com.google.protobuf.ByteString getCommonKey() {
        return commonKey_;
      }
      /**
       * <code>bytes commonKey = 3;</code>
       * @param value The commonKey to set.
       * @return This builder for chaining.
       */
      public Builder setCommonKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        commonKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes commonKey = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommonKey() {
        
        commonKey_ = getDefaultInstance().getCommonKey();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CalCommonKeyResponse)
    }

    // @@protoc_insertion_point(class_scope:CalCommonKeyResponse)
    private static final com.test.proto.CalCommonKeyProto.CalCommonKeyResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.CalCommonKeyProto.CalCommonKeyResponse();
    }

    public static com.test.proto.CalCommonKeyProto.CalCommonKeyResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalCommonKeyResponse>
        PARSER = new com.google.protobuf.AbstractParser<CalCommonKeyResponse>() {
      @java.lang.Override
      public CalCommonKeyResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalCommonKeyResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CalCommonKeyResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalCommonKeyResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.proto.CalCommonKeyProto.CalCommonKeyResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalCommonKeyRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CalCommonKeyRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalCommonKeyResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CalCommonKeyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032cal_common_key_proto.proto\"%\n\023CalCommo" +
      "nKeyRequest\022\016\n\006voteId\030\001 \001(\005\"M\n\024CalCommon" +
      "KeyResponse\022\016\n\006voteId\030\001 \001(\005\022\022\n\nstatusCod" +
      "e\030\002 \001(\005\022\021\n\tcommonKey\030\003 \001(\014B\020\n\016com.test.p" +
      "rotob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CalCommonKeyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CalCommonKeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CalCommonKeyRequest_descriptor,
        new java.lang.String[] { "VoteId", });
    internal_static_CalCommonKeyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CalCommonKeyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CalCommonKeyResponse_descriptor,
        new java.lang.String[] { "VoteId", "StatusCode", "CommonKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
