// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: go_change_selection.proto

package com.test.proto;

public final class ChangeSelectionInfo {
  private ChangeSelectionInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChangeSelectionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChangeSelectionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    int getVoteId();

    /**
     * <code>string selectionId = 2;</code>
     * @return The selectionId.
     */
    java.lang.String getSelectionId();
    /**
     * <code>string selectionId = 2;</code>
     * @return The bytes for selectionId.
     */
    com.google.protobuf.ByteString
        getSelectionIdBytes();

    /**
     * <code>string deadLine = 3;</code>
     * @return The deadLine.
     */
    java.lang.String getDeadLine();
    /**
     * <code>string deadLine = 3;</code>
     * @return The bytes for deadLine.
     */
    com.google.protobuf.ByteString
        getDeadLineBytes();
  }
  /**
   * Protobuf type {@code ChangeSelectionRequest}
   */
  public  static final class ChangeSelectionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChangeSelectionRequest)
      ChangeSelectionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChangeSelectionRequest.newBuilder() to construct.
    private ChangeSelectionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChangeSelectionRequest() {
      selectionId_ = "";
      deadLine_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChangeSelectionRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChangeSelectionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              voteId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              selectionId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              deadLine_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.ChangeSelectionInfo.internal_static_ChangeSelectionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.ChangeSelectionInfo.internal_static_ChangeSelectionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest.class, com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest.Builder.class);
    }

    public static final int VOTEID_FIELD_NUMBER = 1;
    private int voteId_;
    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    public int getVoteId() {
      return voteId_;
    }

    public static final int SELECTIONID_FIELD_NUMBER = 2;
    private volatile java.lang.Object selectionId_;
    /**
     * <code>string selectionId = 2;</code>
     * @return The selectionId.
     */
    public java.lang.String getSelectionId() {
      java.lang.Object ref = selectionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        selectionId_ = s;
        return s;
      }
    }
    /**
     * <code>string selectionId = 2;</code>
     * @return The bytes for selectionId.
     */
    public com.google.protobuf.ByteString
        getSelectionIdBytes() {
      java.lang.Object ref = selectionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        selectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEADLINE_FIELD_NUMBER = 3;
    private volatile java.lang.Object deadLine_;
    /**
     * <code>string deadLine = 3;</code>
     * @return The deadLine.
     */
    public java.lang.String getDeadLine() {
      java.lang.Object ref = deadLine_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deadLine_ = s;
        return s;
      }
    }
    /**
     * <code>string deadLine = 3;</code>
     * @return The bytes for deadLine.
     */
    public com.google.protobuf.ByteString
        getDeadLineBytes() {
      java.lang.Object ref = deadLine_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deadLine_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (voteId_ != 0) {
        output.writeInt32(1, voteId_);
      }
      if (!getSelectionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, selectionId_);
      }
      if (!getDeadLineBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, deadLine_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (voteId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, voteId_);
      }
      if (!getSelectionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, selectionId_);
      }
      if (!getDeadLineBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, deadLine_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest)) {
        return super.equals(obj);
      }
      com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest other = (com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest) obj;

      if (getVoteId()
          != other.getVoteId()) return false;
      if (!getSelectionId()
          .equals(other.getSelectionId())) return false;
      if (!getDeadLine()
          .equals(other.getDeadLine())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOTEID_FIELD_NUMBER;
      hash = (53 * hash) + getVoteId();
      hash = (37 * hash) + SELECTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSelectionId().hashCode();
      hash = (37 * hash) + DEADLINE_FIELD_NUMBER;
      hash = (53 * hash) + getDeadLine().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChangeSelectionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChangeSelectionRequest)
        com.test.proto.ChangeSelectionInfo.ChangeSelectionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.ChangeSelectionInfo.internal_static_ChangeSelectionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.ChangeSelectionInfo.internal_static_ChangeSelectionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest.class, com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest.Builder.class);
      }

      // Construct using com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        voteId_ = 0;

        selectionId_ = "";

        deadLine_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.ChangeSelectionInfo.internal_static_ChangeSelectionRequest_descriptor;
      }

      @java.lang.Override
      public com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest getDefaultInstanceForType() {
        return com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest build() {
        com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest buildPartial() {
        com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest result = new com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest(this);
        result.voteId_ = voteId_;
        result.selectionId_ = selectionId_;
        result.deadLine_ = deadLine_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest) {
          return mergeFrom((com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest other) {
        if (other == com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest.getDefaultInstance()) return this;
        if (other.getVoteId() != 0) {
          setVoteId(other.getVoteId());
        }
        if (!other.getSelectionId().isEmpty()) {
          selectionId_ = other.selectionId_;
          onChanged();
        }
        if (!other.getDeadLine().isEmpty()) {
          deadLine_ = other.deadLine_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int voteId_ ;
      /**
       * <code>int32 voteId = 1;</code>
       * @return The voteId.
       */
      public int getVoteId() {
        return voteId_;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @param value The voteId to set.
       * @return This builder for chaining.
       */
      public Builder setVoteId(int value) {
        
        voteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteId() {
        
        voteId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object selectionId_ = "";
      /**
       * <code>string selectionId = 2;</code>
       * @return The selectionId.
       */
      public java.lang.String getSelectionId() {
        java.lang.Object ref = selectionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          selectionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string selectionId = 2;</code>
       * @return The bytes for selectionId.
       */
      public com.google.protobuf.ByteString
          getSelectionIdBytes() {
        java.lang.Object ref = selectionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          selectionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string selectionId = 2;</code>
       * @param value The selectionId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        selectionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string selectionId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSelectionId() {
        
        selectionId_ = getDefaultInstance().getSelectionId();
        onChanged();
        return this;
      }
      /**
       * <code>string selectionId = 2;</code>
       * @param value The bytes for selectionId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        selectionId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deadLine_ = "";
      /**
       * <code>string deadLine = 3;</code>
       * @return The deadLine.
       */
      public java.lang.String getDeadLine() {
        java.lang.Object ref = deadLine_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deadLine_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string deadLine = 3;</code>
       * @return The bytes for deadLine.
       */
      public com.google.protobuf.ByteString
          getDeadLineBytes() {
        java.lang.Object ref = deadLine_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deadLine_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deadLine = 3;</code>
       * @param value The deadLine to set.
       * @return This builder for chaining.
       */
      public Builder setDeadLine(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deadLine_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deadLine = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeadLine() {
        
        deadLine_ = getDefaultInstance().getDeadLine();
        onChanged();
        return this;
      }
      /**
       * <code>string deadLine = 3;</code>
       * @param value The bytes for deadLine to set.
       * @return This builder for chaining.
       */
      public Builder setDeadLineBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deadLine_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChangeSelectionRequest)
    }

    // @@protoc_insertion_point(class_scope:ChangeSelectionRequest)
    private static final com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest();
    }

    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChangeSelectionRequest>
        PARSER = new com.google.protobuf.AbstractParser<ChangeSelectionRequest>() {
      @java.lang.Override
      public ChangeSelectionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChangeSelectionRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChangeSelectionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChangeSelectionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.proto.ChangeSelectionInfo.ChangeSelectionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChangeSelectionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChangeSelectionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 statusCode = 1;</code>
     * @return The statusCode.
     */
    int getStatusCode();

    /**
     * <code>string extra = 2;</code>
     * @return The extra.
     */
    java.lang.String getExtra();
    /**
     * <code>string extra = 2;</code>
     * @return The bytes for extra.
     */
    com.google.protobuf.ByteString
        getExtraBytes();

    /**
     * <code>string selectionId = 3;</code>
     * @return The selectionId.
     */
    java.lang.String getSelectionId();
    /**
     * <code>string selectionId = 3;</code>
     * @return The bytes for selectionId.
     */
    com.google.protobuf.ByteString
        getSelectionIdBytes();

    /**
     * <code>string deadLine = 4;</code>
     * @return The deadLine.
     */
    java.lang.String getDeadLine();
    /**
     * <code>string deadLine = 4;</code>
     * @return The bytes for deadLine.
     */
    com.google.protobuf.ByteString
        getDeadLineBytes();
  }
  /**
   * <pre>
   * statusCode: 0 - 正常  
   * extra: 错误信息
   * </pre>
   *
   * Protobuf type {@code ChangeSelectionResponse}
   */
  public  static final class ChangeSelectionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChangeSelectionResponse)
      ChangeSelectionResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChangeSelectionResponse.newBuilder() to construct.
    private ChangeSelectionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChangeSelectionResponse() {
      extra_ = "";
      selectionId_ = "";
      deadLine_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChangeSelectionResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChangeSelectionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              statusCode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              extra_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              selectionId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              deadLine_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.ChangeSelectionInfo.internal_static_ChangeSelectionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.ChangeSelectionInfo.internal_static_ChangeSelectionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse.class, com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse.Builder.class);
    }

    public static final int STATUSCODE_FIELD_NUMBER = 1;
    private int statusCode_;
    /**
     * <code>int32 statusCode = 1;</code>
     * @return The statusCode.
     */
    public int getStatusCode() {
      return statusCode_;
    }

    public static final int EXTRA_FIELD_NUMBER = 2;
    private volatile java.lang.Object extra_;
    /**
     * <code>string extra = 2;</code>
     * @return The extra.
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      }
    }
    /**
     * <code>string extra = 2;</code>
     * @return The bytes for extra.
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SELECTIONID_FIELD_NUMBER = 3;
    private volatile java.lang.Object selectionId_;
    /**
     * <code>string selectionId = 3;</code>
     * @return The selectionId.
     */
    public java.lang.String getSelectionId() {
      java.lang.Object ref = selectionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        selectionId_ = s;
        return s;
      }
    }
    /**
     * <code>string selectionId = 3;</code>
     * @return The bytes for selectionId.
     */
    public com.google.protobuf.ByteString
        getSelectionIdBytes() {
      java.lang.Object ref = selectionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        selectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEADLINE_FIELD_NUMBER = 4;
    private volatile java.lang.Object deadLine_;
    /**
     * <code>string deadLine = 4;</code>
     * @return The deadLine.
     */
    public java.lang.String getDeadLine() {
      java.lang.Object ref = deadLine_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deadLine_ = s;
        return s;
      }
    }
    /**
     * <code>string deadLine = 4;</code>
     * @return The bytes for deadLine.
     */
    public com.google.protobuf.ByteString
        getDeadLineBytes() {
      java.lang.Object ref = deadLine_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deadLine_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (statusCode_ != 0) {
        output.writeInt32(1, statusCode_);
      }
      if (!getExtraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, extra_);
      }
      if (!getSelectionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, selectionId_);
      }
      if (!getDeadLineBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deadLine_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (statusCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, statusCode_);
      }
      if (!getExtraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, extra_);
      }
      if (!getSelectionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, selectionId_);
      }
      if (!getDeadLineBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deadLine_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse)) {
        return super.equals(obj);
      }
      com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse other = (com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse) obj;

      if (getStatusCode()
          != other.getStatusCode()) return false;
      if (!getExtra()
          .equals(other.getExtra())) return false;
      if (!getSelectionId()
          .equals(other.getSelectionId())) return false;
      if (!getDeadLine()
          .equals(other.getDeadLine())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusCode();
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + getExtra().hashCode();
      hash = (37 * hash) + SELECTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSelectionId().hashCode();
      hash = (37 * hash) + DEADLINE_FIELD_NUMBER;
      hash = (53 * hash) + getDeadLine().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * statusCode: 0 - 正常  
     * extra: 错误信息
     * </pre>
     *
     * Protobuf type {@code ChangeSelectionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChangeSelectionResponse)
        com.test.proto.ChangeSelectionInfo.ChangeSelectionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.ChangeSelectionInfo.internal_static_ChangeSelectionResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.ChangeSelectionInfo.internal_static_ChangeSelectionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse.class, com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse.Builder.class);
      }

      // Construct using com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        statusCode_ = 0;

        extra_ = "";

        selectionId_ = "";

        deadLine_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.ChangeSelectionInfo.internal_static_ChangeSelectionResponse_descriptor;
      }

      @java.lang.Override
      public com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse getDefaultInstanceForType() {
        return com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse build() {
        com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse buildPartial() {
        com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse result = new com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse(this);
        result.statusCode_ = statusCode_;
        result.extra_ = extra_;
        result.selectionId_ = selectionId_;
        result.deadLine_ = deadLine_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse) {
          return mergeFrom((com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse other) {
        if (other == com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse.getDefaultInstance()) return this;
        if (other.getStatusCode() != 0) {
          setStatusCode(other.getStatusCode());
        }
        if (!other.getExtra().isEmpty()) {
          extra_ = other.extra_;
          onChanged();
        }
        if (!other.getSelectionId().isEmpty()) {
          selectionId_ = other.selectionId_;
          onChanged();
        }
        if (!other.getDeadLine().isEmpty()) {
          deadLine_ = other.deadLine_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int statusCode_ ;
      /**
       * <code>int32 statusCode = 1;</code>
       * @return The statusCode.
       */
      public int getStatusCode() {
        return statusCode_;
      }
      /**
       * <code>int32 statusCode = 1;</code>
       * @param value The statusCode to set.
       * @return This builder for chaining.
       */
      public Builder setStatusCode(int value) {
        
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 statusCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusCode() {
        
        statusCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object extra_ = "";
      /**
       * <code>string extra = 2;</code>
       * @return The extra.
       */
      public java.lang.String getExtra() {
        java.lang.Object ref = extra_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          extra_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string extra = 2;</code>
       * @return The bytes for extra.
       */
      public com.google.protobuf.ByteString
          getExtraBytes() {
        java.lang.Object ref = extra_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extra_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string extra = 2;</code>
       * @param value The extra to set.
       * @return This builder for chaining.
       */
      public Builder setExtra(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string extra = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtra() {
        
        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }
      /**
       * <code>string extra = 2;</code>
       * @param value The bytes for extra to set.
       * @return This builder for chaining.
       */
      public Builder setExtraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extra_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object selectionId_ = "";
      /**
       * <code>string selectionId = 3;</code>
       * @return The selectionId.
       */
      public java.lang.String getSelectionId() {
        java.lang.Object ref = selectionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          selectionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string selectionId = 3;</code>
       * @return The bytes for selectionId.
       */
      public com.google.protobuf.ByteString
          getSelectionIdBytes() {
        java.lang.Object ref = selectionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          selectionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string selectionId = 3;</code>
       * @param value The selectionId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        selectionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string selectionId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSelectionId() {
        
        selectionId_ = getDefaultInstance().getSelectionId();
        onChanged();
        return this;
      }
      /**
       * <code>string selectionId = 3;</code>
       * @param value The bytes for selectionId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        selectionId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deadLine_ = "";
      /**
       * <code>string deadLine = 4;</code>
       * @return The deadLine.
       */
      public java.lang.String getDeadLine() {
        java.lang.Object ref = deadLine_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deadLine_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string deadLine = 4;</code>
       * @return The bytes for deadLine.
       */
      public com.google.protobuf.ByteString
          getDeadLineBytes() {
        java.lang.Object ref = deadLine_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deadLine_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deadLine = 4;</code>
       * @param value The deadLine to set.
       * @return This builder for chaining.
       */
      public Builder setDeadLine(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deadLine_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deadLine = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeadLine() {
        
        deadLine_ = getDefaultInstance().getDeadLine();
        onChanged();
        return this;
      }
      /**
       * <code>string deadLine = 4;</code>
       * @param value The bytes for deadLine to set.
       * @return This builder for chaining.
       */
      public Builder setDeadLineBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deadLine_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChangeSelectionResponse)
    }

    // @@protoc_insertion_point(class_scope:ChangeSelectionResponse)
    private static final com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse();
    }

    public static com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChangeSelectionResponse>
        PARSER = new com.google.protobuf.AbstractParser<ChangeSelectionResponse>() {
      @java.lang.Override
      public ChangeSelectionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChangeSelectionResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChangeSelectionResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChangeSelectionResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.proto.ChangeSelectionInfo.ChangeSelectionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChangeSelectionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChangeSelectionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChangeSelectionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChangeSelectionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031go_change_selection.proto\"O\n\026ChangeSel" +
      "ectionRequest\022\016\n\006voteId\030\001 \001(\005\022\023\n\013selecti" +
      "onId\030\002 \001(\t\022\020\n\010deadLine\030\003 \001(\t\"c\n\027ChangeSe" +
      "lectionResponse\022\022\n\nstatusCode\030\001 \001(\005\022\r\n\005e" +
      "xtra\030\002 \001(\t\022\023\n\013selectionId\030\003 \001(\t\022\020\n\010deadL" +
      "ine\030\004 \001(\tB%\n\016com.test.protoB\023ChangeSelec" +
      "tionInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ChangeSelectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChangeSelectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChangeSelectionRequest_descriptor,
        new java.lang.String[] { "VoteId", "SelectionId", "DeadLine", });
    internal_static_ChangeSelectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ChangeSelectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChangeSelectionResponse_descriptor,
        new java.lang.String[] { "StatusCode", "Extra", "SelectionId", "DeadLine", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
