// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_common_param_proto.proto

package com.test.proto;

public final class GetCommonParamProto {
  private GetCommonParamProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetCommonParamRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetCommonParamRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    int getVoteId();
  }
  /**
   * Protobuf type {@code GetCommonParamRequest}
   */
  public  static final class GetCommonParamRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetCommonParamRequest)
      GetCommonParamRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetCommonParamRequest.newBuilder() to construct.
    private GetCommonParamRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetCommonParamRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetCommonParamRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetCommonParamRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              voteId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.GetCommonParamProto.internal_static_GetCommonParamRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.GetCommonParamProto.internal_static_GetCommonParamRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.GetCommonParamProto.GetCommonParamRequest.class, com.test.proto.GetCommonParamProto.GetCommonParamRequest.Builder.class);
    }

    public static final int VOTEID_FIELD_NUMBER = 1;
    private int voteId_;
    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    public int getVoteId() {
      return voteId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (voteId_ != 0) {
        output.writeInt32(1, voteId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (voteId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, voteId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.proto.GetCommonParamProto.GetCommonParamRequest)) {
        return super.equals(obj);
      }
      com.test.proto.GetCommonParamProto.GetCommonParamRequest other = (com.test.proto.GetCommonParamProto.GetCommonParamRequest) obj;

      if (getVoteId()
          != other.getVoteId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOTEID_FIELD_NUMBER;
      hash = (53 * hash) + getVoteId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.proto.GetCommonParamProto.GetCommonParamRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.GetCommonParamProto.GetCommonParamRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetCommonParamRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetCommonParamRequest)
        com.test.proto.GetCommonParamProto.GetCommonParamRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.GetCommonParamProto.internal_static_GetCommonParamRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.GetCommonParamProto.internal_static_GetCommonParamRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.GetCommonParamProto.GetCommonParamRequest.class, com.test.proto.GetCommonParamProto.GetCommonParamRequest.Builder.class);
      }

      // Construct using com.test.proto.GetCommonParamProto.GetCommonParamRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        voteId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.GetCommonParamProto.internal_static_GetCommonParamRequest_descriptor;
      }

      @java.lang.Override
      public com.test.proto.GetCommonParamProto.GetCommonParamRequest getDefaultInstanceForType() {
        return com.test.proto.GetCommonParamProto.GetCommonParamRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.proto.GetCommonParamProto.GetCommonParamRequest build() {
        com.test.proto.GetCommonParamProto.GetCommonParamRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.proto.GetCommonParamProto.GetCommonParamRequest buildPartial() {
        com.test.proto.GetCommonParamProto.GetCommonParamRequest result = new com.test.proto.GetCommonParamProto.GetCommonParamRequest(this);
        result.voteId_ = voteId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.GetCommonParamProto.GetCommonParamRequest) {
          return mergeFrom((com.test.proto.GetCommonParamProto.GetCommonParamRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.GetCommonParamProto.GetCommonParamRequest other) {
        if (other == com.test.proto.GetCommonParamProto.GetCommonParamRequest.getDefaultInstance()) return this;
        if (other.getVoteId() != 0) {
          setVoteId(other.getVoteId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.GetCommonParamProto.GetCommonParamRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.GetCommonParamProto.GetCommonParamRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int voteId_ ;
      /**
       * <code>int32 voteId = 1;</code>
       * @return The voteId.
       */
      public int getVoteId() {
        return voteId_;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @param value The voteId to set.
       * @return This builder for chaining.
       */
      public Builder setVoteId(int value) {
        
        voteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteId() {
        
        voteId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetCommonParamRequest)
    }

    // @@protoc_insertion_point(class_scope:GetCommonParamRequest)
    private static final com.test.proto.GetCommonParamProto.GetCommonParamRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.GetCommonParamProto.GetCommonParamRequest();
    }

    public static com.test.proto.GetCommonParamProto.GetCommonParamRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetCommonParamRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetCommonParamRequest>() {
      @java.lang.Override
      public GetCommonParamRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetCommonParamRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetCommonParamRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetCommonParamRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.proto.GetCommonParamProto.GetCommonParamRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetCommonParamResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetCommonParamResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 statusCode = 1;</code>
     * @return The statusCode.
     */
    int getStatusCode();

    /**
     * <code>bytes generatorG1 = 2;</code>
     * @return The generatorG1.
     */
    com.google.protobuf.ByteString getGeneratorG1();

    /**
     * <code>bytes selectionId = 3;</code>
     * @return The selectionId.
     */
    com.google.protobuf.ByteString getSelectionId();

    /**
     * <code>string deadLine = 4;</code>
     * @return The deadLine.
     */
    java.lang.String getDeadLine();
    /**
     * <code>string deadLine = 4;</code>
     * @return The bytes for deadLine.
     */
    com.google.protobuf.ByteString
        getDeadLineBytes();

    /**
     * <code>string extra = 5;</code>
     * @return The extra.
     */
    java.lang.String getExtra();
    /**
     * <code>string extra = 5;</code>
     * @return The bytes for extra.
     */
    com.google.protobuf.ByteString
        getExtraBytes();
  }
  /**
   * <pre>
   *1  状态码
   *2  g1生成元
   *3  选举id
   * </pre>
   *
   * Protobuf type {@code GetCommonParamResponse}
   */
  public  static final class GetCommonParamResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetCommonParamResponse)
      GetCommonParamResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetCommonParamResponse.newBuilder() to construct.
    private GetCommonParamResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetCommonParamResponse() {
      generatorG1_ = com.google.protobuf.ByteString.EMPTY;
      selectionId_ = com.google.protobuf.ByteString.EMPTY;
      deadLine_ = "";
      extra_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetCommonParamResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetCommonParamResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              statusCode_ = input.readInt32();
              break;
            }
            case 18: {

              generatorG1_ = input.readBytes();
              break;
            }
            case 26: {

              selectionId_ = input.readBytes();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              deadLine_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              extra_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.GetCommonParamProto.internal_static_GetCommonParamResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.GetCommonParamProto.internal_static_GetCommonParamResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.GetCommonParamProto.GetCommonParamResponse.class, com.test.proto.GetCommonParamProto.GetCommonParamResponse.Builder.class);
    }

    public static final int STATUSCODE_FIELD_NUMBER = 1;
    private int statusCode_;
    /**
     * <code>int32 statusCode = 1;</code>
     * @return The statusCode.
     */
    public int getStatusCode() {
      return statusCode_;
    }

    public static final int GENERATORG1_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString generatorG1_;
    /**
     * <code>bytes generatorG1 = 2;</code>
     * @return The generatorG1.
     */
    public com.google.protobuf.ByteString getGeneratorG1() {
      return generatorG1_;
    }

    public static final int SELECTIONID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString selectionId_;
    /**
     * <code>bytes selectionId = 3;</code>
     * @return The selectionId.
     */
    public com.google.protobuf.ByteString getSelectionId() {
      return selectionId_;
    }

    public static final int DEADLINE_FIELD_NUMBER = 4;
    private volatile java.lang.Object deadLine_;
    /**
     * <code>string deadLine = 4;</code>
     * @return The deadLine.
     */
    public java.lang.String getDeadLine() {
      java.lang.Object ref = deadLine_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deadLine_ = s;
        return s;
      }
    }
    /**
     * <code>string deadLine = 4;</code>
     * @return The bytes for deadLine.
     */
    public com.google.protobuf.ByteString
        getDeadLineBytes() {
      java.lang.Object ref = deadLine_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deadLine_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRA_FIELD_NUMBER = 5;
    private volatile java.lang.Object extra_;
    /**
     * <code>string extra = 5;</code>
     * @return The extra.
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      }
    }
    /**
     * <code>string extra = 5;</code>
     * @return The bytes for extra.
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (statusCode_ != 0) {
        output.writeInt32(1, statusCode_);
      }
      if (!generatorG1_.isEmpty()) {
        output.writeBytes(2, generatorG1_);
      }
      if (!selectionId_.isEmpty()) {
        output.writeBytes(3, selectionId_);
      }
      if (!getDeadLineBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deadLine_);
      }
      if (!getExtraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, extra_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (statusCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, statusCode_);
      }
      if (!generatorG1_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, generatorG1_);
      }
      if (!selectionId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, selectionId_);
      }
      if (!getDeadLineBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deadLine_);
      }
      if (!getExtraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, extra_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.proto.GetCommonParamProto.GetCommonParamResponse)) {
        return super.equals(obj);
      }
      com.test.proto.GetCommonParamProto.GetCommonParamResponse other = (com.test.proto.GetCommonParamProto.GetCommonParamResponse) obj;

      if (getStatusCode()
          != other.getStatusCode()) return false;
      if (!getGeneratorG1()
          .equals(other.getGeneratorG1())) return false;
      if (!getSelectionId()
          .equals(other.getSelectionId())) return false;
      if (!getDeadLine()
          .equals(other.getDeadLine())) return false;
      if (!getExtra()
          .equals(other.getExtra())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusCode();
      hash = (37 * hash) + GENERATORG1_FIELD_NUMBER;
      hash = (53 * hash) + getGeneratorG1().hashCode();
      hash = (37 * hash) + SELECTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSelectionId().hashCode();
      hash = (37 * hash) + DEADLINE_FIELD_NUMBER;
      hash = (53 * hash) + getDeadLine().hashCode();
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + getExtra().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.proto.GetCommonParamProto.GetCommonParamResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.GetCommonParamProto.GetCommonParamResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.GetCommonParamProto.GetCommonParamResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *1  状态码
     *2  g1生成元
     *3  选举id
     * </pre>
     *
     * Protobuf type {@code GetCommonParamResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetCommonParamResponse)
        com.test.proto.GetCommonParamProto.GetCommonParamResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.GetCommonParamProto.internal_static_GetCommonParamResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.GetCommonParamProto.internal_static_GetCommonParamResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.GetCommonParamProto.GetCommonParamResponse.class, com.test.proto.GetCommonParamProto.GetCommonParamResponse.Builder.class);
      }

      // Construct using com.test.proto.GetCommonParamProto.GetCommonParamResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        statusCode_ = 0;

        generatorG1_ = com.google.protobuf.ByteString.EMPTY;

        selectionId_ = com.google.protobuf.ByteString.EMPTY;

        deadLine_ = "";

        extra_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.GetCommonParamProto.internal_static_GetCommonParamResponse_descriptor;
      }

      @java.lang.Override
      public com.test.proto.GetCommonParamProto.GetCommonParamResponse getDefaultInstanceForType() {
        return com.test.proto.GetCommonParamProto.GetCommonParamResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.proto.GetCommonParamProto.GetCommonParamResponse build() {
        com.test.proto.GetCommonParamProto.GetCommonParamResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.proto.GetCommonParamProto.GetCommonParamResponse buildPartial() {
        com.test.proto.GetCommonParamProto.GetCommonParamResponse result = new com.test.proto.GetCommonParamProto.GetCommonParamResponse(this);
        result.statusCode_ = statusCode_;
        result.generatorG1_ = generatorG1_;
        result.selectionId_ = selectionId_;
        result.deadLine_ = deadLine_;
        result.extra_ = extra_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.GetCommonParamProto.GetCommonParamResponse) {
          return mergeFrom((com.test.proto.GetCommonParamProto.GetCommonParamResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.GetCommonParamProto.GetCommonParamResponse other) {
        if (other == com.test.proto.GetCommonParamProto.GetCommonParamResponse.getDefaultInstance()) return this;
        if (other.getStatusCode() != 0) {
          setStatusCode(other.getStatusCode());
        }
        if (other.getGeneratorG1() != com.google.protobuf.ByteString.EMPTY) {
          setGeneratorG1(other.getGeneratorG1());
        }
        if (other.getSelectionId() != com.google.protobuf.ByteString.EMPTY) {
          setSelectionId(other.getSelectionId());
        }
        if (!other.getDeadLine().isEmpty()) {
          deadLine_ = other.deadLine_;
          onChanged();
        }
        if (!other.getExtra().isEmpty()) {
          extra_ = other.extra_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.GetCommonParamProto.GetCommonParamResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.GetCommonParamProto.GetCommonParamResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int statusCode_ ;
      /**
       * <code>int32 statusCode = 1;</code>
       * @return The statusCode.
       */
      public int getStatusCode() {
        return statusCode_;
      }
      /**
       * <code>int32 statusCode = 1;</code>
       * @param value The statusCode to set.
       * @return This builder for chaining.
       */
      public Builder setStatusCode(int value) {
        
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 statusCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusCode() {
        
        statusCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString generatorG1_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes generatorG1 = 2;</code>
       * @return The generatorG1.
       */
      public com.google.protobuf.ByteString getGeneratorG1() {
        return generatorG1_;
      }
      /**
       * <code>bytes generatorG1 = 2;</code>
       * @param value The generatorG1 to set.
       * @return This builder for chaining.
       */
      public Builder setGeneratorG1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        generatorG1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes generatorG1 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGeneratorG1() {
        
        generatorG1_ = getDefaultInstance().getGeneratorG1();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString selectionId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes selectionId = 3;</code>
       * @return The selectionId.
       */
      public com.google.protobuf.ByteString getSelectionId() {
        return selectionId_;
      }
      /**
       * <code>bytes selectionId = 3;</code>
       * @param value The selectionId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectionId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        selectionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes selectionId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSelectionId() {
        
        selectionId_ = getDefaultInstance().getSelectionId();
        onChanged();
        return this;
      }

      private java.lang.Object deadLine_ = "";
      /**
       * <code>string deadLine = 4;</code>
       * @return The deadLine.
       */
      public java.lang.String getDeadLine() {
        java.lang.Object ref = deadLine_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deadLine_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string deadLine = 4;</code>
       * @return The bytes for deadLine.
       */
      public com.google.protobuf.ByteString
          getDeadLineBytes() {
        java.lang.Object ref = deadLine_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deadLine_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deadLine = 4;</code>
       * @param value The deadLine to set.
       * @return This builder for chaining.
       */
      public Builder setDeadLine(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deadLine_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deadLine = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeadLine() {
        
        deadLine_ = getDefaultInstance().getDeadLine();
        onChanged();
        return this;
      }
      /**
       * <code>string deadLine = 4;</code>
       * @param value The bytes for deadLine to set.
       * @return This builder for chaining.
       */
      public Builder setDeadLineBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deadLine_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object extra_ = "";
      /**
       * <code>string extra = 5;</code>
       * @return The extra.
       */
      public java.lang.String getExtra() {
        java.lang.Object ref = extra_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          extra_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string extra = 5;</code>
       * @return The bytes for extra.
       */
      public com.google.protobuf.ByteString
          getExtraBytes() {
        java.lang.Object ref = extra_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extra_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string extra = 5;</code>
       * @param value The extra to set.
       * @return This builder for chaining.
       */
      public Builder setExtra(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string extra = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtra() {
        
        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }
      /**
       * <code>string extra = 5;</code>
       * @param value The bytes for extra to set.
       * @return This builder for chaining.
       */
      public Builder setExtraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extra_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetCommonParamResponse)
    }

    // @@protoc_insertion_point(class_scope:GetCommonParamResponse)
    private static final com.test.proto.GetCommonParamProto.GetCommonParamResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.GetCommonParamProto.GetCommonParamResponse();
    }

    public static com.test.proto.GetCommonParamProto.GetCommonParamResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetCommonParamResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetCommonParamResponse>() {
      @java.lang.Override
      public GetCommonParamResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetCommonParamResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetCommonParamResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetCommonParamResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.proto.GetCommonParamProto.GetCommonParamResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCommonParamRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCommonParamRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCommonParamResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCommonParamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034get_common_param_proto.proto\"\'\n\025GetCom" +
      "monParamRequest\022\016\n\006voteId\030\001 \001(\005\"w\n\026GetCo" +
      "mmonParamResponse\022\022\n\nstatusCode\030\001 \001(\005\022\023\n" +
      "\013generatorG1\030\002 \001(\014\022\023\n\013selectionId\030\003 \001(\014\022" +
      "\020\n\010deadLine\030\004 \001(\t\022\r\n\005extra\030\005 \001(\tB\020\n\016com." +
      "test.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetCommonParamRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetCommonParamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCommonParamRequest_descriptor,
        new java.lang.String[] { "VoteId", });
    internal_static_GetCommonParamResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetCommonParamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCommonParamResponse_descriptor,
        new java.lang.String[] { "StatusCode", "GeneratorG1", "SelectionId", "DeadLine", "Extra", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
