// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: get_vote_result_proto.proto

package com.test.proto;

public final class GetVoteResultProto {
  private GetVoteResultProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetVoteResultRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetVoteResultRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string selectionId = 1;</code>
     * @return The selectionId.
     */
    java.lang.String getSelectionId();
    /**
     * <code>string selectionId = 1;</code>
     * @return The bytes for selectionId.
     */
    com.google.protobuf.ByteString
        getSelectionIdBytes();

    /**
     * <code>int32 voteId = 2;</code>
     * @return The voteId.
     */
    int getVoteId();
  }
  /**
   * Protobuf type {@code GetVoteResultRequest}
   */
  public  static final class GetVoteResultRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetVoteResultRequest)
      GetVoteResultRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetVoteResultRequest.newBuilder() to construct.
    private GetVoteResultRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetVoteResultRequest() {
      selectionId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetVoteResultRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetVoteResultRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              selectionId_ = s;
              break;
            }
            case 16: {

              voteId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.GetVoteResultProto.internal_static_GetVoteResultRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.GetVoteResultProto.internal_static_GetVoteResultRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.GetVoteResultProto.GetVoteResultRequest.class, com.test.proto.GetVoteResultProto.GetVoteResultRequest.Builder.class);
    }

    public static final int SELECTIONID_FIELD_NUMBER = 1;
    private volatile java.lang.Object selectionId_;
    /**
     * <code>string selectionId = 1;</code>
     * @return The selectionId.
     */
    public java.lang.String getSelectionId() {
      java.lang.Object ref = selectionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        selectionId_ = s;
        return s;
      }
    }
    /**
     * <code>string selectionId = 1;</code>
     * @return The bytes for selectionId.
     */
    public com.google.protobuf.ByteString
        getSelectionIdBytes() {
      java.lang.Object ref = selectionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        selectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VOTEID_FIELD_NUMBER = 2;
    private int voteId_;
    /**
     * <code>int32 voteId = 2;</code>
     * @return The voteId.
     */
    public int getVoteId() {
      return voteId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSelectionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, selectionId_);
      }
      if (voteId_ != 0) {
        output.writeInt32(2, voteId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSelectionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, selectionId_);
      }
      if (voteId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, voteId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.proto.GetVoteResultProto.GetVoteResultRequest)) {
        return super.equals(obj);
      }
      com.test.proto.GetVoteResultProto.GetVoteResultRequest other = (com.test.proto.GetVoteResultProto.GetVoteResultRequest) obj;

      if (!getSelectionId()
          .equals(other.getSelectionId())) return false;
      if (getVoteId()
          != other.getVoteId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SELECTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSelectionId().hashCode();
      hash = (37 * hash) + VOTEID_FIELD_NUMBER;
      hash = (53 * hash) + getVoteId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.proto.GetVoteResultProto.GetVoteResultRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.GetVoteResultProto.GetVoteResultRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetVoteResultRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetVoteResultRequest)
        com.test.proto.GetVoteResultProto.GetVoteResultRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.GetVoteResultProto.internal_static_GetVoteResultRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.GetVoteResultProto.internal_static_GetVoteResultRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.GetVoteResultProto.GetVoteResultRequest.class, com.test.proto.GetVoteResultProto.GetVoteResultRequest.Builder.class);
      }

      // Construct using com.test.proto.GetVoteResultProto.GetVoteResultRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        selectionId_ = "";

        voteId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.GetVoteResultProto.internal_static_GetVoteResultRequest_descriptor;
      }

      @java.lang.Override
      public com.test.proto.GetVoteResultProto.GetVoteResultRequest getDefaultInstanceForType() {
        return com.test.proto.GetVoteResultProto.GetVoteResultRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.proto.GetVoteResultProto.GetVoteResultRequest build() {
        com.test.proto.GetVoteResultProto.GetVoteResultRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.proto.GetVoteResultProto.GetVoteResultRequest buildPartial() {
        com.test.proto.GetVoteResultProto.GetVoteResultRequest result = new com.test.proto.GetVoteResultProto.GetVoteResultRequest(this);
        result.selectionId_ = selectionId_;
        result.voteId_ = voteId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.GetVoteResultProto.GetVoteResultRequest) {
          return mergeFrom((com.test.proto.GetVoteResultProto.GetVoteResultRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.GetVoteResultProto.GetVoteResultRequest other) {
        if (other == com.test.proto.GetVoteResultProto.GetVoteResultRequest.getDefaultInstance()) return this;
        if (!other.getSelectionId().isEmpty()) {
          selectionId_ = other.selectionId_;
          onChanged();
        }
        if (other.getVoteId() != 0) {
          setVoteId(other.getVoteId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.GetVoteResultProto.GetVoteResultRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.GetVoteResultProto.GetVoteResultRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object selectionId_ = "";
      /**
       * <code>string selectionId = 1;</code>
       * @return The selectionId.
       */
      public java.lang.String getSelectionId() {
        java.lang.Object ref = selectionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          selectionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string selectionId = 1;</code>
       * @return The bytes for selectionId.
       */
      public com.google.protobuf.ByteString
          getSelectionIdBytes() {
        java.lang.Object ref = selectionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          selectionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string selectionId = 1;</code>
       * @param value The selectionId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        selectionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string selectionId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSelectionId() {
        
        selectionId_ = getDefaultInstance().getSelectionId();
        onChanged();
        return this;
      }
      /**
       * <code>string selectionId = 1;</code>
       * @param value The bytes for selectionId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        selectionId_ = value;
        onChanged();
        return this;
      }

      private int voteId_ ;
      /**
       * <code>int32 voteId = 2;</code>
       * @return The voteId.
       */
      public int getVoteId() {
        return voteId_;
      }
      /**
       * <code>int32 voteId = 2;</code>
       * @param value The voteId to set.
       * @return This builder for chaining.
       */
      public Builder setVoteId(int value) {
        
        voteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 voteId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteId() {
        
        voteId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetVoteResultRequest)
    }

    // @@protoc_insertion_point(class_scope:GetVoteResultRequest)
    private static final com.test.proto.GetVoteResultProto.GetVoteResultRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.GetVoteResultProto.GetVoteResultRequest();
    }

    public static com.test.proto.GetVoteResultProto.GetVoteResultRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetVoteResultRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetVoteResultRequest>() {
      @java.lang.Override
      public GetVoteResultRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetVoteResultRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetVoteResultRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetVoteResultRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.proto.GetVoteResultProto.GetVoteResultRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetVoteResultResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetVoteResultResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    int getVoteId();

    /**
     * <code>int32 statusCode = 2;</code>
     * @return The statusCode.
     */
    int getStatusCode();

    /**
     * <code>int32 voteResult = 3;</code>
     * @return The voteResult.
     */
    int getVoteResult();

    /**
     * <code>string extra = 4;</code>
     * @return The extra.
     */
    java.lang.String getExtra();
    /**
     * <code>string extra = 4;</code>
     * @return The bytes for extra.
     */
    com.google.protobuf.ByteString
        getExtraBytes();

    /**
     * <code>string selectionId = 5;</code>
     * @return The selectionId.
     */
    java.lang.String getSelectionId();
    /**
     * <code>string selectionId = 5;</code>
     * @return The bytes for selectionId.
     */
    com.google.protobuf.ByteString
        getSelectionIdBytes();
  }
  /**
   * <pre>
   * statusCode :
   *   0 - 成功
   *   5 - 其他错误
   * </pre>
   *
   * Protobuf type {@code GetVoteResultResponse}
   */
  public  static final class GetVoteResultResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetVoteResultResponse)
      GetVoteResultResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetVoteResultResponse.newBuilder() to construct.
    private GetVoteResultResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetVoteResultResponse() {
      extra_ = "";
      selectionId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetVoteResultResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetVoteResultResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              voteId_ = input.readInt32();
              break;
            }
            case 16: {

              statusCode_ = input.readInt32();
              break;
            }
            case 24: {

              voteResult_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              extra_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              selectionId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.GetVoteResultProto.internal_static_GetVoteResultResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.GetVoteResultProto.internal_static_GetVoteResultResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.GetVoteResultProto.GetVoteResultResponse.class, com.test.proto.GetVoteResultProto.GetVoteResultResponse.Builder.class);
    }

    public static final int VOTEID_FIELD_NUMBER = 1;
    private int voteId_;
    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    public int getVoteId() {
      return voteId_;
    }

    public static final int STATUSCODE_FIELD_NUMBER = 2;
    private int statusCode_;
    /**
     * <code>int32 statusCode = 2;</code>
     * @return The statusCode.
     */
    public int getStatusCode() {
      return statusCode_;
    }

    public static final int VOTERESULT_FIELD_NUMBER = 3;
    private int voteResult_;
    /**
     * <code>int32 voteResult = 3;</code>
     * @return The voteResult.
     */
    public int getVoteResult() {
      return voteResult_;
    }

    public static final int EXTRA_FIELD_NUMBER = 4;
    private volatile java.lang.Object extra_;
    /**
     * <code>string extra = 4;</code>
     * @return The extra.
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      }
    }
    /**
     * <code>string extra = 4;</code>
     * @return The bytes for extra.
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SELECTIONID_FIELD_NUMBER = 5;
    private volatile java.lang.Object selectionId_;
    /**
     * <code>string selectionId = 5;</code>
     * @return The selectionId.
     */
    public java.lang.String getSelectionId() {
      java.lang.Object ref = selectionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        selectionId_ = s;
        return s;
      }
    }
    /**
     * <code>string selectionId = 5;</code>
     * @return The bytes for selectionId.
     */
    public com.google.protobuf.ByteString
        getSelectionIdBytes() {
      java.lang.Object ref = selectionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        selectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (voteId_ != 0) {
        output.writeInt32(1, voteId_);
      }
      if (statusCode_ != 0) {
        output.writeInt32(2, statusCode_);
      }
      if (voteResult_ != 0) {
        output.writeInt32(3, voteResult_);
      }
      if (!getExtraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, extra_);
      }
      if (!getSelectionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, selectionId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (voteId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, voteId_);
      }
      if (statusCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, statusCode_);
      }
      if (voteResult_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, voteResult_);
      }
      if (!getExtraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, extra_);
      }
      if (!getSelectionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, selectionId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.proto.GetVoteResultProto.GetVoteResultResponse)) {
        return super.equals(obj);
      }
      com.test.proto.GetVoteResultProto.GetVoteResultResponse other = (com.test.proto.GetVoteResultProto.GetVoteResultResponse) obj;

      if (getVoteId()
          != other.getVoteId()) return false;
      if (getStatusCode()
          != other.getStatusCode()) return false;
      if (getVoteResult()
          != other.getVoteResult()) return false;
      if (!getExtra()
          .equals(other.getExtra())) return false;
      if (!getSelectionId()
          .equals(other.getSelectionId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOTEID_FIELD_NUMBER;
      hash = (53 * hash) + getVoteId();
      hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusCode();
      hash = (37 * hash) + VOTERESULT_FIELD_NUMBER;
      hash = (53 * hash) + getVoteResult();
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + getExtra().hashCode();
      hash = (37 * hash) + SELECTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSelectionId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.proto.GetVoteResultProto.GetVoteResultResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.GetVoteResultProto.GetVoteResultResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.GetVoteResultProto.GetVoteResultResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * statusCode :
     *   0 - 成功
     *   5 - 其他错误
     * </pre>
     *
     * Protobuf type {@code GetVoteResultResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetVoteResultResponse)
        com.test.proto.GetVoteResultProto.GetVoteResultResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.GetVoteResultProto.internal_static_GetVoteResultResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.GetVoteResultProto.internal_static_GetVoteResultResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.GetVoteResultProto.GetVoteResultResponse.class, com.test.proto.GetVoteResultProto.GetVoteResultResponse.Builder.class);
      }

      // Construct using com.test.proto.GetVoteResultProto.GetVoteResultResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        voteId_ = 0;

        statusCode_ = 0;

        voteResult_ = 0;

        extra_ = "";

        selectionId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.GetVoteResultProto.internal_static_GetVoteResultResponse_descriptor;
      }

      @java.lang.Override
      public com.test.proto.GetVoteResultProto.GetVoteResultResponse getDefaultInstanceForType() {
        return com.test.proto.GetVoteResultProto.GetVoteResultResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.proto.GetVoteResultProto.GetVoteResultResponse build() {
        com.test.proto.GetVoteResultProto.GetVoteResultResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.proto.GetVoteResultProto.GetVoteResultResponse buildPartial() {
        com.test.proto.GetVoteResultProto.GetVoteResultResponse result = new com.test.proto.GetVoteResultProto.GetVoteResultResponse(this);
        result.voteId_ = voteId_;
        result.statusCode_ = statusCode_;
        result.voteResult_ = voteResult_;
        result.extra_ = extra_;
        result.selectionId_ = selectionId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.GetVoteResultProto.GetVoteResultResponse) {
          return mergeFrom((com.test.proto.GetVoteResultProto.GetVoteResultResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.GetVoteResultProto.GetVoteResultResponse other) {
        if (other == com.test.proto.GetVoteResultProto.GetVoteResultResponse.getDefaultInstance()) return this;
        if (other.getVoteId() != 0) {
          setVoteId(other.getVoteId());
        }
        if (other.getStatusCode() != 0) {
          setStatusCode(other.getStatusCode());
        }
        if (other.getVoteResult() != 0) {
          setVoteResult(other.getVoteResult());
        }
        if (!other.getExtra().isEmpty()) {
          extra_ = other.extra_;
          onChanged();
        }
        if (!other.getSelectionId().isEmpty()) {
          selectionId_ = other.selectionId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.GetVoteResultProto.GetVoteResultResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.GetVoteResultProto.GetVoteResultResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int voteId_ ;
      /**
       * <code>int32 voteId = 1;</code>
       * @return The voteId.
       */
      public int getVoteId() {
        return voteId_;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @param value The voteId to set.
       * @return This builder for chaining.
       */
      public Builder setVoteId(int value) {
        
        voteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteId() {
        
        voteId_ = 0;
        onChanged();
        return this;
      }

      private int statusCode_ ;
      /**
       * <code>int32 statusCode = 2;</code>
       * @return The statusCode.
       */
      public int getStatusCode() {
        return statusCode_;
      }
      /**
       * <code>int32 statusCode = 2;</code>
       * @param value The statusCode to set.
       * @return This builder for chaining.
       */
      public Builder setStatusCode(int value) {
        
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 statusCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusCode() {
        
        statusCode_ = 0;
        onChanged();
        return this;
      }

      private int voteResult_ ;
      /**
       * <code>int32 voteResult = 3;</code>
       * @return The voteResult.
       */
      public int getVoteResult() {
        return voteResult_;
      }
      /**
       * <code>int32 voteResult = 3;</code>
       * @param value The voteResult to set.
       * @return This builder for chaining.
       */
      public Builder setVoteResult(int value) {
        
        voteResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 voteResult = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteResult() {
        
        voteResult_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object extra_ = "";
      /**
       * <code>string extra = 4;</code>
       * @return The extra.
       */
      public java.lang.String getExtra() {
        java.lang.Object ref = extra_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          extra_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string extra = 4;</code>
       * @return The bytes for extra.
       */
      public com.google.protobuf.ByteString
          getExtraBytes() {
        java.lang.Object ref = extra_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extra_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string extra = 4;</code>
       * @param value The extra to set.
       * @return This builder for chaining.
       */
      public Builder setExtra(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string extra = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtra() {
        
        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }
      /**
       * <code>string extra = 4;</code>
       * @param value The bytes for extra to set.
       * @return This builder for chaining.
       */
      public Builder setExtraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extra_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object selectionId_ = "";
      /**
       * <code>string selectionId = 5;</code>
       * @return The selectionId.
       */
      public java.lang.String getSelectionId() {
        java.lang.Object ref = selectionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          selectionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string selectionId = 5;</code>
       * @return The bytes for selectionId.
       */
      public com.google.protobuf.ByteString
          getSelectionIdBytes() {
        java.lang.Object ref = selectionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          selectionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string selectionId = 5;</code>
       * @param value The selectionId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        selectionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string selectionId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSelectionId() {
        
        selectionId_ = getDefaultInstance().getSelectionId();
        onChanged();
        return this;
      }
      /**
       * <code>string selectionId = 5;</code>
       * @param value The bytes for selectionId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        selectionId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetVoteResultResponse)
    }

    // @@protoc_insertion_point(class_scope:GetVoteResultResponse)
    private static final com.test.proto.GetVoteResultProto.GetVoteResultResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.GetVoteResultProto.GetVoteResultResponse();
    }

    public static com.test.proto.GetVoteResultProto.GetVoteResultResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetVoteResultResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetVoteResultResponse>() {
      @java.lang.Override
      public GetVoteResultResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetVoteResultResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetVoteResultResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetVoteResultResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.proto.GetVoteResultProto.GetVoteResultResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetVoteResultRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetVoteResultRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetVoteResultResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetVoteResultResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033get_vote_result_proto.proto\";\n\024GetVote" +
      "ResultRequest\022\023\n\013selectionId\030\001 \001(\t\022\016\n\006vo" +
      "teId\030\002 \001(\005\"s\n\025GetVoteResultResponse\022\016\n\006v" +
      "oteId\030\001 \001(\005\022\022\n\nstatusCode\030\002 \001(\005\022\022\n\nvoteR" +
      "esult\030\003 \001(\005\022\r\n\005extra\030\004 \001(\t\022\023\n\013selectionI" +
      "d\030\005 \001(\tB\020\n\016com.test.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetVoteResultRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetVoteResultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetVoteResultRequest_descriptor,
        new java.lang.String[] { "SelectionId", "VoteId", });
    internal_static_GetVoteResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetVoteResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetVoteResultResponse_descriptor,
        new java.lang.String[] { "VoteId", "StatusCode", "VoteResult", "Extra", "SelectionId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
