// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: go_vote_proto.proto

package com.test.proto;

public final class GoVoteProto {
  private GoVoteProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GoVoteRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GoVoteRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    int getVoteId();

    /**
     * <code>bytes x = 2;</code>
     * @return The x.
     */
    com.google.protobuf.ByteString getX();

    /**
     * <code>bytes y = 3;</code>
     * @return The y.
     */
    com.google.protobuf.ByteString getY();

    /**
     * <code>bytes w = 4;</code>
     * @return The w.
     */
    com.google.protobuf.ByteString getW();

    /**
     * <code>bytes a1 = 5;</code>
     * @return The a1.
     */
    com.google.protobuf.ByteString getA1();

    /**
     * <code>bytes b1 = 6;</code>
     * @return The b1.
     */
    com.google.protobuf.ByteString getB1();

    /**
     * <code>bytes a2 = 7;</code>
     * @return The a2.
     */
    com.google.protobuf.ByteString getA2();

    /**
     * <code>bytes b2 = 8;</code>
     * @return The b2.
     */
    com.google.protobuf.ByteString getB2();

    /**
     * <code>bytes d1 = 9;</code>
     * @return The d1.
     */
    com.google.protobuf.ByteString getD1();

    /**
     * <code>bytes d2 = 10;</code>
     * @return The d2.
     */
    com.google.protobuf.ByteString getD2();

    /**
     * <code>bytes r1 = 11;</code>
     * @return The r1.
     */
    com.google.protobuf.ByteString getR1();

    /**
     * <code>bytes r2 = 12;</code>
     * @return The r2.
     */
    com.google.protobuf.ByteString getR2();

    /**
     * <code>string selectionId = 13;</code>
     * @return The selectionId.
     */
    java.lang.String getSelectionId();
    /**
     * <code>string selectionId = 13;</code>
     * @return The bytes for selectionId.
     */
    com.google.protobuf.ByteString
        getSelectionIdBytes();
  }
  /**
   * Protobuf type {@code GoVoteRequest}
   */
  public  static final class GoVoteRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GoVoteRequest)
      GoVoteRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GoVoteRequest.newBuilder() to construct.
    private GoVoteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GoVoteRequest() {
      x_ = com.google.protobuf.ByteString.EMPTY;
      y_ = com.google.protobuf.ByteString.EMPTY;
      w_ = com.google.protobuf.ByteString.EMPTY;
      a1_ = com.google.protobuf.ByteString.EMPTY;
      b1_ = com.google.protobuf.ByteString.EMPTY;
      a2_ = com.google.protobuf.ByteString.EMPTY;
      b2_ = com.google.protobuf.ByteString.EMPTY;
      d1_ = com.google.protobuf.ByteString.EMPTY;
      d2_ = com.google.protobuf.ByteString.EMPTY;
      r1_ = com.google.protobuf.ByteString.EMPTY;
      r2_ = com.google.protobuf.ByteString.EMPTY;
      selectionId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GoVoteRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GoVoteRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              voteId_ = input.readInt32();
              break;
            }
            case 18: {

              x_ = input.readBytes();
              break;
            }
            case 26: {

              y_ = input.readBytes();
              break;
            }
            case 34: {

              w_ = input.readBytes();
              break;
            }
            case 42: {

              a1_ = input.readBytes();
              break;
            }
            case 50: {

              b1_ = input.readBytes();
              break;
            }
            case 58: {

              a2_ = input.readBytes();
              break;
            }
            case 66: {

              b2_ = input.readBytes();
              break;
            }
            case 74: {

              d1_ = input.readBytes();
              break;
            }
            case 82: {

              d2_ = input.readBytes();
              break;
            }
            case 90: {

              r1_ = input.readBytes();
              break;
            }
            case 98: {

              r2_ = input.readBytes();
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              selectionId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.GoVoteProto.internal_static_GoVoteRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.GoVoteProto.internal_static_GoVoteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.GoVoteProto.GoVoteRequest.class, com.test.proto.GoVoteProto.GoVoteRequest.Builder.class);
    }

    public static final int VOTEID_FIELD_NUMBER = 1;
    private int voteId_;
    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    public int getVoteId() {
      return voteId_;
    }

    public static final int X_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString x_;
    /**
     * <code>bytes x = 2;</code>
     * @return The x.
     */
    public com.google.protobuf.ByteString getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString y_;
    /**
     * <code>bytes y = 3;</code>
     * @return The y.
     */
    public com.google.protobuf.ByteString getY() {
      return y_;
    }

    public static final int W_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString w_;
    /**
     * <code>bytes w = 4;</code>
     * @return The w.
     */
    public com.google.protobuf.ByteString getW() {
      return w_;
    }

    public static final int A1_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString a1_;
    /**
     * <code>bytes a1 = 5;</code>
     * @return The a1.
     */
    public com.google.protobuf.ByteString getA1() {
      return a1_;
    }

    public static final int B1_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString b1_;
    /**
     * <code>bytes b1 = 6;</code>
     * @return The b1.
     */
    public com.google.protobuf.ByteString getB1() {
      return b1_;
    }

    public static final int A2_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString a2_;
    /**
     * <code>bytes a2 = 7;</code>
     * @return The a2.
     */
    public com.google.protobuf.ByteString getA2() {
      return a2_;
    }

    public static final int B2_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString b2_;
    /**
     * <code>bytes b2 = 8;</code>
     * @return The b2.
     */
    public com.google.protobuf.ByteString getB2() {
      return b2_;
    }

    public static final int D1_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString d1_;
    /**
     * <code>bytes d1 = 9;</code>
     * @return The d1.
     */
    public com.google.protobuf.ByteString getD1() {
      return d1_;
    }

    public static final int D2_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString d2_;
    /**
     * <code>bytes d2 = 10;</code>
     * @return The d2.
     */
    public com.google.protobuf.ByteString getD2() {
      return d2_;
    }

    public static final int R1_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString r1_;
    /**
     * <code>bytes r1 = 11;</code>
     * @return The r1.
     */
    public com.google.protobuf.ByteString getR1() {
      return r1_;
    }

    public static final int R2_FIELD_NUMBER = 12;
    private com.google.protobuf.ByteString r2_;
    /**
     * <code>bytes r2 = 12;</code>
     * @return The r2.
     */
    public com.google.protobuf.ByteString getR2() {
      return r2_;
    }

    public static final int SELECTIONID_FIELD_NUMBER = 13;
    private volatile java.lang.Object selectionId_;
    /**
     * <code>string selectionId = 13;</code>
     * @return The selectionId.
     */
    public java.lang.String getSelectionId() {
      java.lang.Object ref = selectionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        selectionId_ = s;
        return s;
      }
    }
    /**
     * <code>string selectionId = 13;</code>
     * @return The bytes for selectionId.
     */
    public com.google.protobuf.ByteString
        getSelectionIdBytes() {
      java.lang.Object ref = selectionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        selectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (voteId_ != 0) {
        output.writeInt32(1, voteId_);
      }
      if (!x_.isEmpty()) {
        output.writeBytes(2, x_);
      }
      if (!y_.isEmpty()) {
        output.writeBytes(3, y_);
      }
      if (!w_.isEmpty()) {
        output.writeBytes(4, w_);
      }
      if (!a1_.isEmpty()) {
        output.writeBytes(5, a1_);
      }
      if (!b1_.isEmpty()) {
        output.writeBytes(6, b1_);
      }
      if (!a2_.isEmpty()) {
        output.writeBytes(7, a2_);
      }
      if (!b2_.isEmpty()) {
        output.writeBytes(8, b2_);
      }
      if (!d1_.isEmpty()) {
        output.writeBytes(9, d1_);
      }
      if (!d2_.isEmpty()) {
        output.writeBytes(10, d2_);
      }
      if (!r1_.isEmpty()) {
        output.writeBytes(11, r1_);
      }
      if (!r2_.isEmpty()) {
        output.writeBytes(12, r2_);
      }
      if (!getSelectionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, selectionId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (voteId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, voteId_);
      }
      if (!x_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, x_);
      }
      if (!y_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, y_);
      }
      if (!w_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, w_);
      }
      if (!a1_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, a1_);
      }
      if (!b1_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, b1_);
      }
      if (!a2_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, a2_);
      }
      if (!b2_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, b2_);
      }
      if (!d1_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, d1_);
      }
      if (!d2_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, d2_);
      }
      if (!r1_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, r1_);
      }
      if (!r2_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, r2_);
      }
      if (!getSelectionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, selectionId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.proto.GoVoteProto.GoVoteRequest)) {
        return super.equals(obj);
      }
      com.test.proto.GoVoteProto.GoVoteRequest other = (com.test.proto.GoVoteProto.GoVoteRequest) obj;

      if (getVoteId()
          != other.getVoteId()) return false;
      if (!getX()
          .equals(other.getX())) return false;
      if (!getY()
          .equals(other.getY())) return false;
      if (!getW()
          .equals(other.getW())) return false;
      if (!getA1()
          .equals(other.getA1())) return false;
      if (!getB1()
          .equals(other.getB1())) return false;
      if (!getA2()
          .equals(other.getA2())) return false;
      if (!getB2()
          .equals(other.getB2())) return false;
      if (!getD1()
          .equals(other.getD1())) return false;
      if (!getD2()
          .equals(other.getD2())) return false;
      if (!getR1()
          .equals(other.getR1())) return false;
      if (!getR2()
          .equals(other.getR2())) return false;
      if (!getSelectionId()
          .equals(other.getSelectionId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOTEID_FIELD_NUMBER;
      hash = (53 * hash) + getVoteId();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX().hashCode();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY().hashCode();
      hash = (37 * hash) + W_FIELD_NUMBER;
      hash = (53 * hash) + getW().hashCode();
      hash = (37 * hash) + A1_FIELD_NUMBER;
      hash = (53 * hash) + getA1().hashCode();
      hash = (37 * hash) + B1_FIELD_NUMBER;
      hash = (53 * hash) + getB1().hashCode();
      hash = (37 * hash) + A2_FIELD_NUMBER;
      hash = (53 * hash) + getA2().hashCode();
      hash = (37 * hash) + B2_FIELD_NUMBER;
      hash = (53 * hash) + getB2().hashCode();
      hash = (37 * hash) + D1_FIELD_NUMBER;
      hash = (53 * hash) + getD1().hashCode();
      hash = (37 * hash) + D2_FIELD_NUMBER;
      hash = (53 * hash) + getD2().hashCode();
      hash = (37 * hash) + R1_FIELD_NUMBER;
      hash = (53 * hash) + getR1().hashCode();
      hash = (37 * hash) + R2_FIELD_NUMBER;
      hash = (53 * hash) + getR2().hashCode();
      hash = (37 * hash) + SELECTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSelectionId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.proto.GoVoteProto.GoVoteRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GoVoteProto.GoVoteRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GoVoteProto.GoVoteRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GoVoteProto.GoVoteRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GoVoteProto.GoVoteRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GoVoteProto.GoVoteRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GoVoteProto.GoVoteRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.GoVoteProto.GoVoteRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.GoVoteProto.GoVoteRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.proto.GoVoteProto.GoVoteRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.GoVoteProto.GoVoteRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.GoVoteProto.GoVoteRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.GoVoteProto.GoVoteRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GoVoteRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GoVoteRequest)
        com.test.proto.GoVoteProto.GoVoteRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.GoVoteProto.internal_static_GoVoteRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.GoVoteProto.internal_static_GoVoteRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.GoVoteProto.GoVoteRequest.class, com.test.proto.GoVoteProto.GoVoteRequest.Builder.class);
      }

      // Construct using com.test.proto.GoVoteProto.GoVoteRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        voteId_ = 0;

        x_ = com.google.protobuf.ByteString.EMPTY;

        y_ = com.google.protobuf.ByteString.EMPTY;

        w_ = com.google.protobuf.ByteString.EMPTY;

        a1_ = com.google.protobuf.ByteString.EMPTY;

        b1_ = com.google.protobuf.ByteString.EMPTY;

        a2_ = com.google.protobuf.ByteString.EMPTY;

        b2_ = com.google.protobuf.ByteString.EMPTY;

        d1_ = com.google.protobuf.ByteString.EMPTY;

        d2_ = com.google.protobuf.ByteString.EMPTY;

        r1_ = com.google.protobuf.ByteString.EMPTY;

        r2_ = com.google.protobuf.ByteString.EMPTY;

        selectionId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.GoVoteProto.internal_static_GoVoteRequest_descriptor;
      }

      @java.lang.Override
      public com.test.proto.GoVoteProto.GoVoteRequest getDefaultInstanceForType() {
        return com.test.proto.GoVoteProto.GoVoteRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.proto.GoVoteProto.GoVoteRequest build() {
        com.test.proto.GoVoteProto.GoVoteRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.proto.GoVoteProto.GoVoteRequest buildPartial() {
        com.test.proto.GoVoteProto.GoVoteRequest result = new com.test.proto.GoVoteProto.GoVoteRequest(this);
        result.voteId_ = voteId_;
        result.x_ = x_;
        result.y_ = y_;
        result.w_ = w_;
        result.a1_ = a1_;
        result.b1_ = b1_;
        result.a2_ = a2_;
        result.b2_ = b2_;
        result.d1_ = d1_;
        result.d2_ = d2_;
        result.r1_ = r1_;
        result.r2_ = r2_;
        result.selectionId_ = selectionId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.GoVoteProto.GoVoteRequest) {
          return mergeFrom((com.test.proto.GoVoteProto.GoVoteRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.GoVoteProto.GoVoteRequest other) {
        if (other == com.test.proto.GoVoteProto.GoVoteRequest.getDefaultInstance()) return this;
        if (other.getVoteId() != 0) {
          setVoteId(other.getVoteId());
        }
        if (other.getX() != com.google.protobuf.ByteString.EMPTY) {
          setX(other.getX());
        }
        if (other.getY() != com.google.protobuf.ByteString.EMPTY) {
          setY(other.getY());
        }
        if (other.getW() != com.google.protobuf.ByteString.EMPTY) {
          setW(other.getW());
        }
        if (other.getA1() != com.google.protobuf.ByteString.EMPTY) {
          setA1(other.getA1());
        }
        if (other.getB1() != com.google.protobuf.ByteString.EMPTY) {
          setB1(other.getB1());
        }
        if (other.getA2() != com.google.protobuf.ByteString.EMPTY) {
          setA2(other.getA2());
        }
        if (other.getB2() != com.google.protobuf.ByteString.EMPTY) {
          setB2(other.getB2());
        }
        if (other.getD1() != com.google.protobuf.ByteString.EMPTY) {
          setD1(other.getD1());
        }
        if (other.getD2() != com.google.protobuf.ByteString.EMPTY) {
          setD2(other.getD2());
        }
        if (other.getR1() != com.google.protobuf.ByteString.EMPTY) {
          setR1(other.getR1());
        }
        if (other.getR2() != com.google.protobuf.ByteString.EMPTY) {
          setR2(other.getR2());
        }
        if (!other.getSelectionId().isEmpty()) {
          selectionId_ = other.selectionId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.GoVoteProto.GoVoteRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.GoVoteProto.GoVoteRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int voteId_ ;
      /**
       * <code>int32 voteId = 1;</code>
       * @return The voteId.
       */
      public int getVoteId() {
        return voteId_;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @param value The voteId to set.
       * @return This builder for chaining.
       */
      public Builder setVoteId(int value) {
        
        voteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteId() {
        
        voteId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString x_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes x = 2;</code>
       * @return The x.
       */
      public com.google.protobuf.ByteString getX() {
        return x_;
      }
      /**
       * <code>bytes x = 2;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes x = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        
        x_ = getDefaultInstance().getX();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString y_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes y = 3;</code>
       * @return The y.
       */
      public com.google.protobuf.ByteString getY() {
        return y_;
      }
      /**
       * <code>bytes y = 3;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes y = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        
        y_ = getDefaultInstance().getY();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString w_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes w = 4;</code>
       * @return The w.
       */
      public com.google.protobuf.ByteString getW() {
        return w_;
      }
      /**
       * <code>bytes w = 4;</code>
       * @param value The w to set.
       * @return This builder for chaining.
       */
      public Builder setW(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        w_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes w = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearW() {
        
        w_ = getDefaultInstance().getW();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString a1_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes a1 = 5;</code>
       * @return The a1.
       */
      public com.google.protobuf.ByteString getA1() {
        return a1_;
      }
      /**
       * <code>bytes a1 = 5;</code>
       * @param value The a1 to set.
       * @return This builder for chaining.
       */
      public Builder setA1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        a1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes a1 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearA1() {
        
        a1_ = getDefaultInstance().getA1();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString b1_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes b1 = 6;</code>
       * @return The b1.
       */
      public com.google.protobuf.ByteString getB1() {
        return b1_;
      }
      /**
       * <code>bytes b1 = 6;</code>
       * @param value The b1 to set.
       * @return This builder for chaining.
       */
      public Builder setB1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        b1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes b1 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearB1() {
        
        b1_ = getDefaultInstance().getB1();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString a2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes a2 = 7;</code>
       * @return The a2.
       */
      public com.google.protobuf.ByteString getA2() {
        return a2_;
      }
      /**
       * <code>bytes a2 = 7;</code>
       * @param value The a2 to set.
       * @return This builder for chaining.
       */
      public Builder setA2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        a2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes a2 = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearA2() {
        
        a2_ = getDefaultInstance().getA2();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString b2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes b2 = 8;</code>
       * @return The b2.
       */
      public com.google.protobuf.ByteString getB2() {
        return b2_;
      }
      /**
       * <code>bytes b2 = 8;</code>
       * @param value The b2 to set.
       * @return This builder for chaining.
       */
      public Builder setB2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        b2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes b2 = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearB2() {
        
        b2_ = getDefaultInstance().getB2();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString d1_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes d1 = 9;</code>
       * @return The d1.
       */
      public com.google.protobuf.ByteString getD1() {
        return d1_;
      }
      /**
       * <code>bytes d1 = 9;</code>
       * @param value The d1 to set.
       * @return This builder for chaining.
       */
      public Builder setD1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        d1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes d1 = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearD1() {
        
        d1_ = getDefaultInstance().getD1();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString d2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes d2 = 10;</code>
       * @return The d2.
       */
      public com.google.protobuf.ByteString getD2() {
        return d2_;
      }
      /**
       * <code>bytes d2 = 10;</code>
       * @param value The d2 to set.
       * @return This builder for chaining.
       */
      public Builder setD2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        d2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes d2 = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearD2() {
        
        d2_ = getDefaultInstance().getD2();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString r1_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes r1 = 11;</code>
       * @return The r1.
       */
      public com.google.protobuf.ByteString getR1() {
        return r1_;
      }
      /**
       * <code>bytes r1 = 11;</code>
       * @param value The r1 to set.
       * @return This builder for chaining.
       */
      public Builder setR1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        r1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes r1 = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearR1() {
        
        r1_ = getDefaultInstance().getR1();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString r2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes r2 = 12;</code>
       * @return The r2.
       */
      public com.google.protobuf.ByteString getR2() {
        return r2_;
      }
      /**
       * <code>bytes r2 = 12;</code>
       * @param value The r2 to set.
       * @return This builder for chaining.
       */
      public Builder setR2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        r2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes r2 = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearR2() {
        
        r2_ = getDefaultInstance().getR2();
        onChanged();
        return this;
      }

      private java.lang.Object selectionId_ = "";
      /**
       * <code>string selectionId = 13;</code>
       * @return The selectionId.
       */
      public java.lang.String getSelectionId() {
        java.lang.Object ref = selectionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          selectionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string selectionId = 13;</code>
       * @return The bytes for selectionId.
       */
      public com.google.protobuf.ByteString
          getSelectionIdBytes() {
        java.lang.Object ref = selectionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          selectionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string selectionId = 13;</code>
       * @param value The selectionId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        selectionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string selectionId = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearSelectionId() {
        
        selectionId_ = getDefaultInstance().getSelectionId();
        onChanged();
        return this;
      }
      /**
       * <code>string selectionId = 13;</code>
       * @param value The bytes for selectionId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        selectionId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GoVoteRequest)
    }

    // @@protoc_insertion_point(class_scope:GoVoteRequest)
    private static final com.test.proto.GoVoteProto.GoVoteRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.GoVoteProto.GoVoteRequest();
    }

    public static com.test.proto.GoVoteProto.GoVoteRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GoVoteRequest>
        PARSER = new com.google.protobuf.AbstractParser<GoVoteRequest>() {
      @java.lang.Override
      public GoVoteRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GoVoteRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GoVoteRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GoVoteRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.proto.GoVoteProto.GoVoteRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GoVoteResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GoVoteResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    int getVoteId();

    /**
     * <code>int32 statusCode = 2;</code>
     * @return The statusCode.
     */
    int getStatusCode();

    /**
     * <code>string selectionId = 3;</code>
     * @return The selectionId.
     */
    java.lang.String getSelectionId();
    /**
     * <code>string selectionId = 3;</code>
     * @return The bytes for selectionId.
     */
    com.google.protobuf.ByteString
        getSelectionIdBytes();

    /**
     * <code>string extra = 4;</code>
     * @return The extra.
     */
    java.lang.String getExtra();
    /**
     * <code>string extra = 4;</code>
     * @return The bytes for extra.
     */
    com.google.protobuf.ByteString
        getExtraBytes();
  }
  /**
   * <pre>
   * statusCode :
   *   0 - 投票成功
   *   1 - 当前选举id重复投票
   *   2 - 零知识证明失败
   *   3 - 其他错误
   * </pre>
   *
   * Protobuf type {@code GoVoteResponse}
   */
  public  static final class GoVoteResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GoVoteResponse)
      GoVoteResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GoVoteResponse.newBuilder() to construct.
    private GoVoteResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GoVoteResponse() {
      selectionId_ = "";
      extra_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GoVoteResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GoVoteResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              voteId_ = input.readInt32();
              break;
            }
            case 16: {

              statusCode_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              selectionId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              extra_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.GoVoteProto.internal_static_GoVoteResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.GoVoteProto.internal_static_GoVoteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.GoVoteProto.GoVoteResponse.class, com.test.proto.GoVoteProto.GoVoteResponse.Builder.class);
    }

    public static final int VOTEID_FIELD_NUMBER = 1;
    private int voteId_;
    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    public int getVoteId() {
      return voteId_;
    }

    public static final int STATUSCODE_FIELD_NUMBER = 2;
    private int statusCode_;
    /**
     * <code>int32 statusCode = 2;</code>
     * @return The statusCode.
     */
    public int getStatusCode() {
      return statusCode_;
    }

    public static final int SELECTIONID_FIELD_NUMBER = 3;
    private volatile java.lang.Object selectionId_;
    /**
     * <code>string selectionId = 3;</code>
     * @return The selectionId.
     */
    public java.lang.String getSelectionId() {
      java.lang.Object ref = selectionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        selectionId_ = s;
        return s;
      }
    }
    /**
     * <code>string selectionId = 3;</code>
     * @return The bytes for selectionId.
     */
    public com.google.protobuf.ByteString
        getSelectionIdBytes() {
      java.lang.Object ref = selectionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        selectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRA_FIELD_NUMBER = 4;
    private volatile java.lang.Object extra_;
    /**
     * <code>string extra = 4;</code>
     * @return The extra.
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      }
    }
    /**
     * <code>string extra = 4;</code>
     * @return The bytes for extra.
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (voteId_ != 0) {
        output.writeInt32(1, voteId_);
      }
      if (statusCode_ != 0) {
        output.writeInt32(2, statusCode_);
      }
      if (!getSelectionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, selectionId_);
      }
      if (!getExtraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, extra_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (voteId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, voteId_);
      }
      if (statusCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, statusCode_);
      }
      if (!getSelectionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, selectionId_);
      }
      if (!getExtraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, extra_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.proto.GoVoteProto.GoVoteResponse)) {
        return super.equals(obj);
      }
      com.test.proto.GoVoteProto.GoVoteResponse other = (com.test.proto.GoVoteProto.GoVoteResponse) obj;

      if (getVoteId()
          != other.getVoteId()) return false;
      if (getStatusCode()
          != other.getStatusCode()) return false;
      if (!getSelectionId()
          .equals(other.getSelectionId())) return false;
      if (!getExtra()
          .equals(other.getExtra())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOTEID_FIELD_NUMBER;
      hash = (53 * hash) + getVoteId();
      hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusCode();
      hash = (37 * hash) + SELECTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSelectionId().hashCode();
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + getExtra().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.proto.GoVoteProto.GoVoteResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GoVoteProto.GoVoteResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GoVoteProto.GoVoteResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GoVoteProto.GoVoteResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GoVoteProto.GoVoteResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.GoVoteProto.GoVoteResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.GoVoteProto.GoVoteResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.GoVoteProto.GoVoteResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.GoVoteProto.GoVoteResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.proto.GoVoteProto.GoVoteResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.GoVoteProto.GoVoteResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.GoVoteProto.GoVoteResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.GoVoteProto.GoVoteResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * statusCode :
     *   0 - 投票成功
     *   1 - 当前选举id重复投票
     *   2 - 零知识证明失败
     *   3 - 其他错误
     * </pre>
     *
     * Protobuf type {@code GoVoteResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GoVoteResponse)
        com.test.proto.GoVoteProto.GoVoteResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.GoVoteProto.internal_static_GoVoteResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.GoVoteProto.internal_static_GoVoteResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.GoVoteProto.GoVoteResponse.class, com.test.proto.GoVoteProto.GoVoteResponse.Builder.class);
      }

      // Construct using com.test.proto.GoVoteProto.GoVoteResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        voteId_ = 0;

        statusCode_ = 0;

        selectionId_ = "";

        extra_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.GoVoteProto.internal_static_GoVoteResponse_descriptor;
      }

      @java.lang.Override
      public com.test.proto.GoVoteProto.GoVoteResponse getDefaultInstanceForType() {
        return com.test.proto.GoVoteProto.GoVoteResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.proto.GoVoteProto.GoVoteResponse build() {
        com.test.proto.GoVoteProto.GoVoteResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.proto.GoVoteProto.GoVoteResponse buildPartial() {
        com.test.proto.GoVoteProto.GoVoteResponse result = new com.test.proto.GoVoteProto.GoVoteResponse(this);
        result.voteId_ = voteId_;
        result.statusCode_ = statusCode_;
        result.selectionId_ = selectionId_;
        result.extra_ = extra_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.GoVoteProto.GoVoteResponse) {
          return mergeFrom((com.test.proto.GoVoteProto.GoVoteResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.GoVoteProto.GoVoteResponse other) {
        if (other == com.test.proto.GoVoteProto.GoVoteResponse.getDefaultInstance()) return this;
        if (other.getVoteId() != 0) {
          setVoteId(other.getVoteId());
        }
        if (other.getStatusCode() != 0) {
          setStatusCode(other.getStatusCode());
        }
        if (!other.getSelectionId().isEmpty()) {
          selectionId_ = other.selectionId_;
          onChanged();
        }
        if (!other.getExtra().isEmpty()) {
          extra_ = other.extra_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.GoVoteProto.GoVoteResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.GoVoteProto.GoVoteResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int voteId_ ;
      /**
       * <code>int32 voteId = 1;</code>
       * @return The voteId.
       */
      public int getVoteId() {
        return voteId_;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @param value The voteId to set.
       * @return This builder for chaining.
       */
      public Builder setVoteId(int value) {
        
        voteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteId() {
        
        voteId_ = 0;
        onChanged();
        return this;
      }

      private int statusCode_ ;
      /**
       * <code>int32 statusCode = 2;</code>
       * @return The statusCode.
       */
      public int getStatusCode() {
        return statusCode_;
      }
      /**
       * <code>int32 statusCode = 2;</code>
       * @param value The statusCode to set.
       * @return This builder for chaining.
       */
      public Builder setStatusCode(int value) {
        
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 statusCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusCode() {
        
        statusCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object selectionId_ = "";
      /**
       * <code>string selectionId = 3;</code>
       * @return The selectionId.
       */
      public java.lang.String getSelectionId() {
        java.lang.Object ref = selectionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          selectionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string selectionId = 3;</code>
       * @return The bytes for selectionId.
       */
      public com.google.protobuf.ByteString
          getSelectionIdBytes() {
        java.lang.Object ref = selectionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          selectionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string selectionId = 3;</code>
       * @param value The selectionId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        selectionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string selectionId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSelectionId() {
        
        selectionId_ = getDefaultInstance().getSelectionId();
        onChanged();
        return this;
      }
      /**
       * <code>string selectionId = 3;</code>
       * @param value The bytes for selectionId to set.
       * @return This builder for chaining.
       */
      public Builder setSelectionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        selectionId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object extra_ = "";
      /**
       * <code>string extra = 4;</code>
       * @return The extra.
       */
      public java.lang.String getExtra() {
        java.lang.Object ref = extra_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          extra_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string extra = 4;</code>
       * @return The bytes for extra.
       */
      public com.google.protobuf.ByteString
          getExtraBytes() {
        java.lang.Object ref = extra_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extra_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string extra = 4;</code>
       * @param value The extra to set.
       * @return This builder for chaining.
       */
      public Builder setExtra(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string extra = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtra() {
        
        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }
      /**
       * <code>string extra = 4;</code>
       * @param value The bytes for extra to set.
       * @return This builder for chaining.
       */
      public Builder setExtraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extra_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GoVoteResponse)
    }

    // @@protoc_insertion_point(class_scope:GoVoteResponse)
    private static final com.test.proto.GoVoteProto.GoVoteResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.GoVoteProto.GoVoteResponse();
    }

    public static com.test.proto.GoVoteProto.GoVoteResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GoVoteResponse>
        PARSER = new com.google.protobuf.AbstractParser<GoVoteResponse>() {
      @java.lang.Override
      public GoVoteResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GoVoteResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GoVoteResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GoVoteResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.proto.GoVoteProto.GoVoteResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GoVoteRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GoVoteRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GoVoteResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GoVoteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023go_vote_proto.proto\"\265\001\n\rGoVoteRequest\022" +
      "\016\n\006voteId\030\001 \001(\005\022\t\n\001x\030\002 \001(\014\022\t\n\001y\030\003 \001(\014\022\t\n" +
      "\001w\030\004 \001(\014\022\n\n\002a1\030\005 \001(\014\022\n\n\002b1\030\006 \001(\014\022\n\n\002a2\030\007" +
      " \001(\014\022\n\n\002b2\030\010 \001(\014\022\n\n\002d1\030\t \001(\014\022\n\n\002d2\030\n \001(\014" +
      "\022\n\n\002r1\030\013 \001(\014\022\n\n\002r2\030\014 \001(\014\022\023\n\013selectionId\030" +
      "\r \001(\t\"X\n\016GoVoteResponse\022\016\n\006voteId\030\001 \001(\005\022" +
      "\022\n\nstatusCode\030\002 \001(\005\022\023\n\013selectionId\030\003 \001(\t" +
      "\022\r\n\005extra\030\004 \001(\tB\020\n\016com.test.protob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GoVoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GoVoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GoVoteRequest_descriptor,
        new java.lang.String[] { "VoteId", "X", "Y", "W", "A1", "B1", "A2", "B2", "D1", "D2", "R1", "R2", "SelectionId", });
    internal_static_GoVoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GoVoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GoVoteResponse_descriptor,
        new java.lang.String[] { "VoteId", "StatusCode", "SelectionId", "Extra", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
