// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: public_key_proto.proto

package com.test.proto;

public final class PublicKeyProto {
  private PublicKeyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BoardcastPublicKeyRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BoardcastPublicKeyRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    int getVoteId();

    /**
     * <code>bytes publickey = 2;</code>
     * @return The publickey.
     */
    com.google.protobuf.ByteString getPublickey();

    /**
     * <code>bytes gq = 3;</code>
     * @return The gq.
     */
    com.google.protobuf.ByteString getGq();

    /**
     * <code>bytes r = 4;</code>
     * @return The r.
     */
    com.google.protobuf.ByteString getR();
  }
  /**
   * Protobuf type {@code BoardcastPublicKeyRequest}
   */
  public  static final class BoardcastPublicKeyRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BoardcastPublicKeyRequest)
      BoardcastPublicKeyRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BoardcastPublicKeyRequest.newBuilder() to construct.
    private BoardcastPublicKeyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BoardcastPublicKeyRequest() {
      publickey_ = com.google.protobuf.ByteString.EMPTY;
      gq_ = com.google.protobuf.ByteString.EMPTY;
      r_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BoardcastPublicKeyRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BoardcastPublicKeyRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              voteId_ = input.readInt32();
              break;
            }
            case 18: {

              publickey_ = input.readBytes();
              break;
            }
            case 26: {

              gq_ = input.readBytes();
              break;
            }
            case 34: {

              r_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.PublicKeyProto.internal_static_BoardcastPublicKeyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.PublicKeyProto.internal_static_BoardcastPublicKeyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest.class, com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest.Builder.class);
    }

    public static final int VOTEID_FIELD_NUMBER = 1;
    private int voteId_;
    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    public int getVoteId() {
      return voteId_;
    }

    public static final int PUBLICKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString publickey_;
    /**
     * <code>bytes publickey = 2;</code>
     * @return The publickey.
     */
    public com.google.protobuf.ByteString getPublickey() {
      return publickey_;
    }

    public static final int GQ_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString gq_;
    /**
     * <code>bytes gq = 3;</code>
     * @return The gq.
     */
    public com.google.protobuf.ByteString getGq() {
      return gq_;
    }

    public static final int R_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString r_;
    /**
     * <code>bytes r = 4;</code>
     * @return The r.
     */
    public com.google.protobuf.ByteString getR() {
      return r_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (voteId_ != 0) {
        output.writeInt32(1, voteId_);
      }
      if (!publickey_.isEmpty()) {
        output.writeBytes(2, publickey_);
      }
      if (!gq_.isEmpty()) {
        output.writeBytes(3, gq_);
      }
      if (!r_.isEmpty()) {
        output.writeBytes(4, r_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (voteId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, voteId_);
      }
      if (!publickey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, publickey_);
      }
      if (!gq_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, gq_);
      }
      if (!r_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, r_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest)) {
        return super.equals(obj);
      }
      com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest other = (com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest) obj;

      if (getVoteId()
          != other.getVoteId()) return false;
      if (!getPublickey()
          .equals(other.getPublickey())) return false;
      if (!getGq()
          .equals(other.getGq())) return false;
      if (!getR()
          .equals(other.getR())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOTEID_FIELD_NUMBER;
      hash = (53 * hash) + getVoteId();
      hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublickey().hashCode();
      hash = (37 * hash) + GQ_FIELD_NUMBER;
      hash = (53 * hash) + getGq().hashCode();
      hash = (37 * hash) + R_FIELD_NUMBER;
      hash = (53 * hash) + getR().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BoardcastPublicKeyRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BoardcastPublicKeyRequest)
        com.test.proto.PublicKeyProto.BoardcastPublicKeyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.PublicKeyProto.internal_static_BoardcastPublicKeyRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.PublicKeyProto.internal_static_BoardcastPublicKeyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest.class, com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest.Builder.class);
      }

      // Construct using com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        voteId_ = 0;

        publickey_ = com.google.protobuf.ByteString.EMPTY;

        gq_ = com.google.protobuf.ByteString.EMPTY;

        r_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.PublicKeyProto.internal_static_BoardcastPublicKeyRequest_descriptor;
      }

      @java.lang.Override
      public com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest getDefaultInstanceForType() {
        return com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest build() {
        com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest buildPartial() {
        com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest result = new com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest(this);
        result.voteId_ = voteId_;
        result.publickey_ = publickey_;
        result.gq_ = gq_;
        result.r_ = r_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest) {
          return mergeFrom((com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest other) {
        if (other == com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest.getDefaultInstance()) return this;
        if (other.getVoteId() != 0) {
          setVoteId(other.getVoteId());
        }
        if (other.getPublickey() != com.google.protobuf.ByteString.EMPTY) {
          setPublickey(other.getPublickey());
        }
        if (other.getGq() != com.google.protobuf.ByteString.EMPTY) {
          setGq(other.getGq());
        }
        if (other.getR() != com.google.protobuf.ByteString.EMPTY) {
          setR(other.getR());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int voteId_ ;
      /**
       * <code>int32 voteId = 1;</code>
       * @return The voteId.
       */
      public int getVoteId() {
        return voteId_;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @param value The voteId to set.
       * @return This builder for chaining.
       */
      public Builder setVoteId(int value) {
        
        voteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteId() {
        
        voteId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString publickey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes publickey = 2;</code>
       * @return The publickey.
       */
      public com.google.protobuf.ByteString getPublickey() {
        return publickey_;
      }
      /**
       * <code>bytes publickey = 2;</code>
       * @param value The publickey to set.
       * @return This builder for chaining.
       */
      public Builder setPublickey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publickey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes publickey = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublickey() {
        
        publickey_ = getDefaultInstance().getPublickey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString gq_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes gq = 3;</code>
       * @return The gq.
       */
      public com.google.protobuf.ByteString getGq() {
        return gq_;
      }
      /**
       * <code>bytes gq = 3;</code>
       * @param value The gq to set.
       * @return This builder for chaining.
       */
      public Builder setGq(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes gq = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGq() {
        
        gq_ = getDefaultInstance().getGq();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString r_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes r = 4;</code>
       * @return The r.
       */
      public com.google.protobuf.ByteString getR() {
        return r_;
      }
      /**
       * <code>bytes r = 4;</code>
       * @param value The r to set.
       * @return This builder for chaining.
       */
      public Builder setR(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        r_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes r = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearR() {
        
        r_ = getDefaultInstance().getR();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BoardcastPublicKeyRequest)
    }

    // @@protoc_insertion_point(class_scope:BoardcastPublicKeyRequest)
    private static final com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest();
    }

    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BoardcastPublicKeyRequest>
        PARSER = new com.google.protobuf.AbstractParser<BoardcastPublicKeyRequest>() {
      @java.lang.Override
      public BoardcastPublicKeyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BoardcastPublicKeyRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BoardcastPublicKeyRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BoardcastPublicKeyRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.proto.PublicKeyProto.BoardcastPublicKeyRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BoardcastPublicKeyResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BoardcastPublicKeyResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    int getVoteId();

    /**
     * <code>int32 statusCode = 2;</code>
     * @return The statusCode.
     */
    int getStatusCode();
  }
  /**
   * <pre>
   * statusCode:  
   *     0 - 正常
   *     1 - 重复传播了
   * </pre>
   *
   * Protobuf type {@code BoardcastPublicKeyResponse}
   */
  public  static final class BoardcastPublicKeyResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BoardcastPublicKeyResponse)
      BoardcastPublicKeyResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BoardcastPublicKeyResponse.newBuilder() to construct.
    private BoardcastPublicKeyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BoardcastPublicKeyResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BoardcastPublicKeyResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BoardcastPublicKeyResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              voteId_ = input.readInt32();
              break;
            }
            case 16: {

              statusCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.proto.PublicKeyProto.internal_static_BoardcastPublicKeyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.proto.PublicKeyProto.internal_static_BoardcastPublicKeyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse.class, com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse.Builder.class);
    }

    public static final int VOTEID_FIELD_NUMBER = 1;
    private int voteId_;
    /**
     * <code>int32 voteId = 1;</code>
     * @return The voteId.
     */
    public int getVoteId() {
      return voteId_;
    }

    public static final int STATUSCODE_FIELD_NUMBER = 2;
    private int statusCode_;
    /**
     * <code>int32 statusCode = 2;</code>
     * @return The statusCode.
     */
    public int getStatusCode() {
      return statusCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (voteId_ != 0) {
        output.writeInt32(1, voteId_);
      }
      if (statusCode_ != 0) {
        output.writeInt32(2, statusCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (voteId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, voteId_);
      }
      if (statusCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, statusCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse)) {
        return super.equals(obj);
      }
      com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse other = (com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse) obj;

      if (getVoteId()
          != other.getVoteId()) return false;
      if (getStatusCode()
          != other.getStatusCode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOTEID_FIELD_NUMBER;
      hash = (53 * hash) + getVoteId();
      hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * statusCode:  
     *     0 - 正常
     *     1 - 重复传播了
     * </pre>
     *
     * Protobuf type {@code BoardcastPublicKeyResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BoardcastPublicKeyResponse)
        com.test.proto.PublicKeyProto.BoardcastPublicKeyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.test.proto.PublicKeyProto.internal_static_BoardcastPublicKeyResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.test.proto.PublicKeyProto.internal_static_BoardcastPublicKeyResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse.class, com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse.Builder.class);
      }

      // Construct using com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        voteId_ = 0;

        statusCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.test.proto.PublicKeyProto.internal_static_BoardcastPublicKeyResponse_descriptor;
      }

      @java.lang.Override
      public com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse getDefaultInstanceForType() {
        return com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse build() {
        com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse buildPartial() {
        com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse result = new com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse(this);
        result.voteId_ = voteId_;
        result.statusCode_ = statusCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse) {
          return mergeFrom((com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse other) {
        if (other == com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse.getDefaultInstance()) return this;
        if (other.getVoteId() != 0) {
          setVoteId(other.getVoteId());
        }
        if (other.getStatusCode() != 0) {
          setStatusCode(other.getStatusCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int voteId_ ;
      /**
       * <code>int32 voteId = 1;</code>
       * @return The voteId.
       */
      public int getVoteId() {
        return voteId_;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @param value The voteId to set.
       * @return This builder for chaining.
       */
      public Builder setVoteId(int value) {
        
        voteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 voteId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteId() {
        
        voteId_ = 0;
        onChanged();
        return this;
      }

      private int statusCode_ ;
      /**
       * <code>int32 statusCode = 2;</code>
       * @return The statusCode.
       */
      public int getStatusCode() {
        return statusCode_;
      }
      /**
       * <code>int32 statusCode = 2;</code>
       * @param value The statusCode to set.
       * @return This builder for chaining.
       */
      public Builder setStatusCode(int value) {
        
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 statusCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusCode() {
        
        statusCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BoardcastPublicKeyResponse)
    }

    // @@protoc_insertion_point(class_scope:BoardcastPublicKeyResponse)
    private static final com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse();
    }

    public static com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BoardcastPublicKeyResponse>
        PARSER = new com.google.protobuf.AbstractParser<BoardcastPublicKeyResponse>() {
      @java.lang.Override
      public BoardcastPublicKeyResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BoardcastPublicKeyResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BoardcastPublicKeyResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BoardcastPublicKeyResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.test.proto.PublicKeyProto.BoardcastPublicKeyResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BoardcastPublicKeyRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BoardcastPublicKeyRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BoardcastPublicKeyResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BoardcastPublicKeyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026public_key_proto.proto\"U\n\031BoardcastPub" +
      "licKeyRequest\022\016\n\006voteId\030\001 \001(\005\022\021\n\tpublick" +
      "ey\030\002 \001(\014\022\n\n\002gq\030\003 \001(\014\022\t\n\001r\030\004 \001(\014\"@\n\032Board" +
      "castPublicKeyResponse\022\016\n\006voteId\030\001 \001(\005\022\022\n" +
      "\nstatusCode\030\002 \001(\005B\020\n\016com.test.protob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BoardcastPublicKeyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BoardcastPublicKeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BoardcastPublicKeyRequest_descriptor,
        new java.lang.String[] { "VoteId", "Publickey", "Gq", "R", });
    internal_static_BoardcastPublicKeyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BoardcastPublicKeyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BoardcastPublicKeyResponse_descriptor,
        new java.lang.String[] { "VoteId", "StatusCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
